// ============================================================
// Enums — Todos os tipos enum do domínio OpenBusinessOS
// ============================================================

/** Nichos de mercado suportados pelo sistema */
export enum Niche {
  RETAIL = 'RETAIL',
  ECOMMERCE = 'ECOMMERCE',
  FOOD_SERVICE = 'FOOD_SERVICE',
  PROFESSIONAL_SERVICES = 'PROFESSIONAL_SERVICES',
  HEALTH_CARE = 'HEALTH_CARE',
  EDUCATION = 'EDUCATION',
  CONSTRUCTION = 'CONSTRUCTION',
  BEAUTY = 'BEAUTY',
  FITNESS = 'FITNESS',
  LEGAL = 'LEGAL',
  ACCOUNTING = 'ACCOUNTING',
  TECH_SERVICES = 'TECH_SERVICES',
  REAL_ESTATE = 'REAL_ESTATE',
  AUTOMOTIVE = 'AUTOMOTIVE',
  AGRICULTURE = 'AGRICULTURE',
  OTHER = 'OTHER',
}

/** Sub-nichos de mercado — refinamento por segmento */
export enum SubNiche {
  // RETAIL
  RETAIL_CLOTHING = 'RETAIL_CLOTHING',
  RETAIL_GROCERY = 'RETAIL_GROCERY',
  RETAIL_ELECTRONICS = 'RETAIL_ELECTRONICS',
  RETAIL_FURNITURE = 'RETAIL_FURNITURE',
  RETAIL_PHARMACY = 'RETAIL_PHARMACY',
  RETAIL_GENERAL = 'RETAIL_GENERAL',
  // ECOMMERCE
  ECOM_DIGITAL_PRODUCTS = 'ECOM_DIGITAL_PRODUCTS',
  ECOM_MARKETPLACE_SELLER = 'ECOM_MARKETPLACE_SELLER',
  ECOM_D2C_BRAND = 'ECOM_D2C_BRAND',
  ECOM_DROP = 'ECOM_DROP',
  ECOM_SUBSCRIPTION = 'ECOM_SUBSCRIPTION',
  // FOOD_SERVICE
  FOOD_RESTAURANT = 'FOOD_RESTAURANT',
  FOOD_CAFE = 'FOOD_CAFE',
  FOOD_BAKERY = 'FOOD_BAKERY',
  FOOD_BAR_PUB = 'FOOD_BAR_PUB',
  FOOD_DELIVERY_CLOUD = 'FOOD_DELIVERY_CLOUD',
  FOOD_CATERING = 'FOOD_CATERING',
  // PROFESSIONAL_SERVICES
  PROF_CONSULTING = 'PROF_CONSULTING',
  PROF_MARKETING_AGENCY = 'PROF_MARKETING_AGENCY',
  PROF_DESIGN_STUDIO = 'PROF_DESIGN_STUDIO',
  PROF_FREELANCER = 'PROF_FREELANCER',
  // HEALTH_CARE
  HEALTH_CLINIC = 'HEALTH_CLINIC',
  HEALTH_DENTISTRY = 'HEALTH_DENTISTRY',
  HEALTH_PHYSIOTHERAPY = 'HEALTH_PHYSIOTHERAPY',
  HEALTH_PSYCHOLOGY = 'HEALTH_PSYCHOLOGY',
  HEALTH_NUTRITION = 'HEALTH_NUTRITION',
  // EDUCATION
  EDU_SCHOOL = 'EDU_SCHOOL',
  EDU_COURSE_PLATFORM = 'EDU_COURSE_PLATFORM',
  EDU_TUTORING = 'EDU_TUTORING',
  EDU_LANGUAGE_SCHOOL = 'EDU_LANGUAGE_SCHOOL',
  // CONSTRUCTION
  CONST_GENERAL = 'CONST_GENERAL',
  CONST_RENOVATION = 'CONST_RENOVATION',
  CONST_SPECIALIZED = 'CONST_SPECIALIZED',
  CONST_MATERIALS = 'CONST_MATERIALS',
  // BEAUTY
  BEAUTY_SALON = 'BEAUTY_SALON',
  BEAUTY_BARBERSHOP = 'BEAUTY_BARBERSHOP',
  BEAUTY_NAIL_STUDIO = 'BEAUTY_NAIL_STUDIO',
  BEAUTY_AESTHETIC = 'BEAUTY_AESTHETIC',
  // FITNESS
  FIT_GYM = 'FIT_GYM',
  FIT_STUDIO = 'FIT_STUDIO',
  FIT_PERSONAL_TRAINER = 'FIT_PERSONAL_TRAINER',
  // LEGAL
  LEGAL_LAW_FIRM = 'LEGAL_LAW_FIRM',
  LEGAL_SOLO_PRACTITIONER = 'LEGAL_SOLO_PRACTITIONER',
  // ACCOUNTING
  ACCT_FIRM = 'ACCT_FIRM',
  ACCT_SOLO = 'ACCT_SOLO',
  // TECH_SERVICES
  TECH_AGENCY = 'TECH_AGENCY',
  TECH_SAAS = 'TECH_SAAS',
  TECH_MAINTENANCE = 'TECH_MAINTENANCE',
  // REAL_ESTATE
  RE_BROKERAGE = 'RE_BROKERAGE',
  RE_PROPERTY_MGMT = 'RE_PROPERTY_MGMT',
  RE_DEVELOPMENT = 'RE_DEVELOPMENT',
  // AUTOMOTIVE
  AUTO_REPAIR = 'AUTO_REPAIR',
  AUTO_DEALERSHIP = 'AUTO_DEALERSHIP',
  AUTO_PARTS = 'AUTO_PARTS',
  // AGRICULTURE
  AGRI_FARM = 'AGRI_FARM',
  AGRI_AGRIBUSINESS = 'AGRI_AGRIBUSINESS',
  AGRI_COOPERATIVE = 'AGRI_COOPERATIVE',
  // OTHER
  OTHER_GENERAL = 'OTHER_GENERAL',
}

/** Tipos de transação financeira */
export enum TransactionType {
  SALE = 'SALE',
  PURCHASE = 'PURCHASE',
  EXPENSE = 'EXPENSE',
  RECEIVABLE = 'RECEIVABLE',
  PAYABLE = 'PAYABLE',
  TRANSFER = 'TRANSFER',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}

/** Status de uma transação */
export enum TransactionStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

/** Métodos de pagamento aceitos */
export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  PIX = 'PIX',
  BOLETO = 'BOLETO',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
  OTHER = 'OTHER',
}

/** Tipos de passo em um workflow */
export enum WorkflowStepType {
  TRIGGER = 'TRIGGER',
  CONDITION = 'CONDITION',
  ACTION = 'ACTION',
  DELAY = 'DELAY',
  NOTIFICATION = 'NOTIFICATION',
  WEBHOOK = 'WEBHOOK',
  LOOP = 'LOOP',
  PARALLEL = 'PARALLEL',
}

/** Status de um workflow */
export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

/** Status de uma execução de workflow */
export enum WorkflowExecutionStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMED_OUT = 'TIMED_OUT',
}

/** Status de um passo do workflow */
export enum WorkflowStepStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

/** Severidade de um evento */
export enum EventSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

/** Status de um evento */
export enum EventStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

/** Papel do usuário na organização */
export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  VIEWER = 'VIEWER',
}

/** Ações de permissão */
export enum PermissionAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  MANAGE = 'MANAGE',
}

/** Recursos do sistema para permissão */
export enum PermissionResource {
  ORGANIZATION = 'ORGANIZATION',
  USERS = 'USERS',
  FINANCIAL = 'FINANCIAL',
  CRM = 'CRM',
  PRODUCTS = 'PRODUCTS',
  WORKFLOWS = 'WORKFLOWS',
  ANALYTICS = 'ANALYTICS',
  SETTINGS = 'SETTINGS',
}

/** Status de um cliente */
export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  LEAD = 'LEAD',
  CHURNED = 'CHURNED',
}

/** Segmento de cliente */
export enum CustomerSegment {
  VIP = 'VIP',
  REGULAR = 'REGULAR',
  NEW = 'NEW',
  AT_RISK = 'AT_RISK',
  CHURNED = 'CHURNED',
}

/** Status de um produto */
export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DISCONTINUED = 'DISCONTINUED',
}

/** Tipo de dashboard */
export enum DashboardType {
  FINANCIAL = 'FINANCIAL',
  SALES = 'SALES',
  CRM = 'CRM',
  OPERATIONS = 'OPERATIONS',
  CUSTOM = 'CUSTOM',
}

/** Status do onboarding */
export enum OnboardingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
