import { Niche, TemplateType } from '@prisma/client';

interface TemplateSeed {
  niche: Niche;
  type: TemplateType;
  name: string;
  description: string;
  content: Record<string, any>;
  isDefault: boolean;
}

// ─── TECH_SERVICES ─────────────────────────────────────────────────────────
const TECH_SERVICES_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.TECH_SERVICES, type: TemplateType.WORKFLOW, name: 'Cobrança de Assinatura', description: 'Workflow de cobrança para SaaS/serviços tech', isDefault: true, content: { steps: [{ id: 1, name: 'Fatura Automática', trigger: 'billing_cycle', action: 'generate_invoice' }, { id: 2, name: 'Email Fatura', trigger: 'invoice_generated', action: 'send_email', template: 'fatura-saas' }, { id: 3, name: 'Lembrete Vencimento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-pagamento' }, { id: 4, name: 'Downgrade/Suspensão', trigger: 'invoice_overdue_15d', action: 'downgrade_plan' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente SaaS', description: 'Fluxo de boas-vindas e ativação', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'signup_completed', action: 'send_email', template: 'boas-vindas-saas' }, { id: 2, name: 'Tutorial Guiado', trigger: 'first_login', action: 'show_onboarding' }, { id: 3, name: 'Check 7d', trigger: 'timer_7d', action: 'send_email', template: 'check-ativacao' }, { id: 4, name: 'CS Outreach', trigger: 'low_usage_14d', action: 'notify', target: 'customer_success' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.WORKFLOW, name: 'Suporte Ticket', description: 'Fluxo de atendimento de tickets de suporte', isDefault: true, content: { steps: [{ id: 1, name: 'Auto-resposta', trigger: 'ticket_created', action: 'send_email', template: 'ticket-recebido' }, { id: 2, name: 'Classificar', trigger: 'ticket_open', action: 'auto_classify' }, { id: 3, name: 'Escalar', trigger: 'no_response_4h', action: 'notify', target: 'support_lead' }, { id: 4, name: 'Pesquisa Satisfação', trigger: 'ticket_resolved', action: 'send_email', template: 'nps-suporte' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.WORKFLOW, name: 'Churn Prevention', description: 'Prevenção de cancelamento de assinatura', isDefault: false, content: { steps: [{ id: 1, name: 'Detectar Risco', trigger: 'low_usage_7d', action: 'notify', target: 'cs' }, { id: 2, name: 'Oferta Retenção', trigger: 'churn_signal', action: 'send_email', template: 'oferta-retencao' }, { id: 3, name: 'Follow-up CS', trigger: 'timer_3d', action: 'call_customer' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.WORKFLOW, name: 'Deploy Notification', description: 'Notificação de deploy para clientes', isDefault: false, content: { steps: [{ id: 1, name: 'Changelog', trigger: 'deploy_completed', action: 'send_email', template: 'changelog-update' }, { id: 2, name: 'Release Notes', trigger: 'major_release', action: 'send_email', template: 'release-notes' }] } },
  // 3 DASHBOARD
  { niche: Niche.TECH_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard SaaS', description: 'Métricas SaaS (MRR, churn, LTV)', isDefault: true, content: { widgets: [{ type: 'mrr', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'active_subscriptions', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'churn_rate', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'ltv_cac_ratio', position: { x: 0, y: 4, w: 6, h: 4 } }, { type: 'mrr_growth', position: { x: 6, y: 4, w: 6, h: 4 } }], filters: ['period', 'plan'] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard de Suporte', description: 'Métricas de atendimento ao cliente', isDefault: false, content: { widgets: [{ type: 'open_tickets', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'avg_response_time', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'satisfaction_score', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'tickets_trend', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'agent'] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard de Produto', description: 'Uso de features e engajamento', isDefault: false, content: { widgets: [{ type: 'dau_mau', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'feature_usage', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'activation_funnel', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'cohort'] } },
  // 4 EMAIL
  { niche: Niche.TECH_SERVICES, type: TemplateType.EMAIL, name: 'Boas-vindas SaaS', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) ao {{product_name}}!', body: 'Olá {{customer_name}},\n\nSua conta foi criada com sucesso!\n\nComece com nosso tutorial rápido e configure tudo em 5 minutos.\n\nSe precisar de ajuda, nosso suporte está disponível.', from: 'suporte@{{company_domain}}' } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.EMAIL, name: 'Fatura SaaS', description: 'Email com fatura de assinatura', isDefault: true, content: { subject: 'Fatura #{{invoice_number}} - {{product_name}}', body: 'Olá {{customer_name}},\n\nPlano: {{plan_name}}\nValor: R$ {{amount}}\nVencimento: {{due_date}}\n\nGerencie sua assinatura no painel.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.EMAIL, name: 'Ticket Recebido', description: 'Auto-resposta para ticket de suporte', isDefault: true, content: { subject: 'Ticket #{{ticket_id}} recebido', body: 'Olá {{customer_name}},\n\nRecebemos sua solicitação (#{{ticket_id}}).\n\nNossa equipe retornará em até {{sla_response_time}}.\n\nAcompanhe pelo painel.', from: 'suporte@{{company_domain}}' } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.EMAIL, name: 'Changelog', description: 'Email com novidades da plataforma', isDefault: false, content: { subject: 'Novidades do {{product_name}} - {{month}}', body: 'Olá {{customer_name}},\n\nNovas features:\n{{changelog_items}}\n\nConfira!', from: 'product@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.TECH_SERVICES, type: TemplateType.REPORT, name: 'DRE SaaS', description: 'DRE para empresa de tecnologia/SaaS', isDefault: true, content: { sections: [{ title: 'Receita', items: ['mrr', 'setup_fees', 'one_time', 'services'] }, { title: 'Custos', items: ['infra_cloud', 'api_costs', 'support_costs'] }, { title: 'Despesas', items: ['pessoal', 'marketing', 'sistemas', 'escritorio', 'impostos'] }, { title: 'Métricas', items: ['mrr', 'arr', 'ltv', 'cac', 'payback_months'] }], period: 'monthly' } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.REPORT, name: 'Relatório de Assinaturas', description: 'Análise de base de assinantes', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_ativos', 'novos_mes', 'cancelamentos', 'churn_rate'] }, { title: 'Por Plano', items: ['assinantes_por_plano', 'mrr_por_plano', 'upgrade_downgrade'] }, { title: 'Métricas', items: ['arpu', 'ltv', 'expansion_revenue'] }], period: 'monthly' } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.REPORT, name: 'Relatório de Suporte', description: 'Métricas de atendimento ao cliente', isDefault: false, content: { sections: [{ title: 'Volume', items: ['tickets_mes', 'tickets_por_canal', 'tickets_por_categoria'] }, { title: 'SLA', items: ['tempo_resposta_medio', 'taxa_dentro_sla', 'taxa_resolucao_primeiro_contato'] }, { title: 'Satisfação', items: ['csat_medio', 'nps', 'feedback_negativo'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.TECH_SERVICES, type: TemplateType.INVOICE, name: 'NFS-e SaaS', description: 'NFS-e para serviço de software', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.04', natureza: 'Serviço de Tecnologia', campos_adicionais: ['plano', 'periodo', 'usuarios'] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.INVOICE, name: 'Invoice Internacional', description: 'Invoice em inglês para clientes internacionais', isDefault: false, content: { formato: 'internacional', idioma: 'en', campos: ['invoice_number', 'date', 'customer', 'plan', 'period', 'amount', 'currency'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.TECH_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Planos SaaS', description: 'Categorias de planos de software', isDefault: true, content: { categories: ['Free', 'Starter', 'Pro', 'Enterprise', 'Add-ons', 'Consultoria', 'Setup', 'Treinamento'] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Tech', description: 'Unidades de medida para SaaS', isDefault: true, content: { units: [{ code: 'MENS', name: 'Mensalidade' }, { code: 'USER', name: 'Usuário/Mês' }, { code: 'API', name: 'Chamada API' }, { code: 'GB', name: 'GB Armazenado' }, { code: 'H', name: 'Hora' }, { code: 'SETUP', name: 'Setup' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Margens SaaS', description: 'Margens por tipo de plano', isDefault: false, content: { margins: [{ category: 'SaaS', margin: 0.75 }, { category: 'Consultoria', margin: 0.55 }, { category: 'Setup', margin: 0.60 }, { category: 'Add-ons', margin: 0.80 }] } },
  // 2 ONBOARDING
  { niche: Niche.TECH_SERVICES, type: TemplateType.ONBOARDING, name: 'Setup SaaS', description: 'Configuração inicial para empresa de software', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Empresa', fields: ['cnpj', 'razao_social', 'site'] }, { id: 2, title: 'Configurar Planos', action: 'create_plans' }, { id: 3, title: 'Integrar Gateway', fields: ['stripe', 'pagseguro', 'mercadopago'] }, { id: 4, title: 'Configurar Produto', action: 'setup_product' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.ONBOARDING, name: 'Migração de Base', description: 'Migrar clientes de outra plataforma', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Usuários', action: 'import_users' }, { id: 3, title: 'Migrar Assinaturas', action: 'import_subscriptions' }, { id: 4, title: 'Testar', action: 'test' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.TECH_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'Métricas SaaS', description: 'Dashboard de métricas SaaS padrão', isDefault: true, content: { metrics: ['mrr', 'arr', 'churn_rate', 'arpu', 'ltv', 'cac', 'payback_months', 'expansion_revenue'], benchmarks: { good_churn: 0.05, good_ltv_cac: 3, good_payback: 12 } } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'Feature Flags', description: 'Configuração de feature flags para rollout', isDefault: true, content: { strategies: ['percentage', 'user_list', 'plan_based', 'gradual'], default_off: true, audit_enabled: true } },
  { niche: Niche.TECH_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'SLA de Disponibilidade', description: 'Configuração de SLA para clientes', isDefault: false, content: { tiers: [{ name: 'Standard', uptime: 99.5, support_hours: 'business', response_time: '24h' }, { name: 'Premium', uptime: 99.9, support_hours: 'extended', response_time: '4h' }, { name: 'Enterprise', uptime: 99.99, support_hours: '24/7', response_time: '1h' }] } },
];

// ─── REAL_ESTATE ───────────────────────────────────────────────────────────
const REAL_ESTATE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.REAL_ESTATE, type: TemplateType.WORKFLOW, name: 'Cobrança de Aluguel', description: 'Workflow de cobrança de aluguel', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Boleto', trigger: 'rent_5d_before_due', action: 'send_email', template: 'boleto-aluguel' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'rent_due_date', action: 'send_sms', template: 'vencimento-hoje' }, { id: 3, name: 'Aviso Atraso', trigger: 'rent_overdue_3d', action: 'send_email', template: 'aluguel-atrasado' }, { id: 4, name: 'Notificar Proprietário', trigger: 'rent_overdue_10d', action: 'notify', target: 'owner' }, { id: 5, name: 'Multa e Juros', trigger: 'rent_overdue_1d', action: 'apply_penalty', fine_pct: 10, interest_monthly: 1 }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.WORKFLOW, name: 'Onboarding de Inquilino', description: 'Fluxo de entrada de novo inquilino', isDefault: true, content: { steps: [{ id: 1, name: 'Contrato Assinado', trigger: 'lease_signed', action: 'send_email', template: 'contrato-assinado' }, { id: 2, name: 'Vistoria Inicial', trigger: 'timer_3d', action: 'schedule_inspection' }, { id: 3, name: 'Entrega Chaves', trigger: 'inspection_done', action: 'confirm_delivery' }, { id: 4, name: 'Configurar Cobrança', trigger: 'keys_delivered', action: 'setup_billing' }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.WORKFLOW, name: 'Vistoria de Saída', description: 'Processo de vistoria e devolução', isDefault: true, content: { steps: [{ id: 1, name: 'Aviso de Saída', trigger: 'notice_given', action: 'create_task', type: 'move_out_inspection' }, { id: 2, name: 'Agendar Vistoria', trigger: 'notice_30d_before', action: 'schedule_inspection' }, { id: 3, name: 'Realizar Vistoria', trigger: 'inspection_date', action: 'create_checklist' }, { id: 4, name: 'Desconto Caução', trigger: 'damages_found', action: 'calculate_deduction' }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.WORKFLOW, name: 'Renovação de Contrato', description: 'Processo de renovação de locação', isDefault: false, content: { steps: [{ id: 1, name: 'Alerta 60d', trigger: 'lease_expires_60d', action: 'notify', target: 'manager' }, { id: 2, name: 'Propor Renovação', trigger: 'timer_5d', action: 'send_email', template: 'renovacao-contrato' }, { id: 3, name: 'Reajuste', trigger: 'renewal_accepted', action: 'apply_adjustment', index: 'igpm' }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.WORKFLOW, name: 'Manutenção de Imóvel', description: 'Fluxo de solicitação de manutenção', isDefault: false, content: { steps: [{ id: 1, name: 'Solicitação Recebida', trigger: 'maintenance_requested', action: 'create_ticket' }, { id: 2, name: 'Classificar Urgência', trigger: 'ticket_created', action: 'classify_priority' }, { id: 3, name: 'Enviar Prestador', trigger: 'classified', action: 'notify', target: 'contractor' }, { id: 4, name: 'Confirmar Conclusão', trigger: 'work_done', action: 'verify_completion' }] } },
  // 3 DASHBOARD
  { niche: Niche.REAL_ESTATE, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira da imobiliária', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'commissions', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'occupancy_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'property_type'] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.DASHBOARD, name: 'Dashboard de Imóveis', description: 'Gestão de portfólio de imóveis', isDefault: false, content: { widgets: [{ type: 'total_properties', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'vacancy_rate', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'by_type', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'by_region', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['type', 'region', 'status'] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.DASHBOARD, name: 'Dashboard de Inadimplência', description: 'Aluguéis em atraso', isDefault: false, content: { widgets: [{ type: 'total_overdue', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'aging_chart', position: { x: 4, y: 0, w: 8, h: 4 } }, { type: 'overdue_by_property', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'region'] } },
  // 4 EMAIL
  { niche: Niche.REAL_ESTATE, type: TemplateType.EMAIL, name: 'Boas-vindas Inquilino', description: 'Email de boas-vindas para novo inquilino', isDefault: true, content: { subject: 'Bem-vindo(a) ao seu novo lar!', body: 'Olá {{tenant_name}},\n\nSeu contrato de locação está ativo.\nImóvel: {{property_address}}\nAluguel: R$ {{rent_amount}}\nVencimento: dia {{due_day}}\n\nBem-vindo(a)!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.EMAIL, name: 'Boleto de Aluguel', description: 'Email com boleto de aluguel', isDefault: true, content: { subject: 'Aluguel {{month}} - {{property_address}}', body: 'Olá {{tenant_name}},\n\nAluguel de {{month}}: R$ {{amount}}\nVencimento: {{due_date}}\n\nPIX: {{pix_key}}\nBoleto em anexo.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.EMAIL, name: 'Aluguel Atrasado', description: 'Email de aviso de aluguel em atraso', isDefault: true, content: { subject: 'Aluguel em atraso - {{property_address}}', body: 'Olá {{tenant_name}},\n\nO aluguel de {{month}} está {{days_overdue}} dias em atraso.\n\nValor com multa e juros: R$ {{amount_with_penalty}}\n\nRegularize para evitar ações.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.EMAIL, name: 'Relatório para Proprietário', description: 'Relatório mensal para proprietário', isDefault: false, content: { subject: 'Relatório do imóvel - {{month}}', body: 'Olá {{owner_name}},\n\nResumo do mês:\n- Aluguel recebido: R$ {{rent_received}}\n- Descontos (condomínio, IPTU): R$ {{deductions}}\n- Repasses: R$ {{net_amount}}\n- Inadimplência: {{overdue_status}}', from: 'relacionamento@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.REAL_ESTATE, type: TemplateType.REPORT, name: 'DRE Imobiliária', description: 'DRE para imobiliária', isDefault: true, content: { sections: [{ title: 'Receita', items: ['comissoes_locacao', 'comissoes_venda', 'taxas_administrativas', 'condominio'] }, { title: 'Custos', items: ['manutencao_imoveis', 'comissoes_corretores'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.REPORT, name: 'Relatório de Ocupação', description: 'Análise de ocupação do portfólio', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_imoveis', 'ocupados', 'vagos', 'taxa_ocupacao'] }, { title: 'Por Tipo', items: ['apartamentos', 'casas', 'comercial', 'salas'] }, { title: 'Por Região', items: ['imoveis_por_bairro', 'aluguel_medio_bairro'] }], period: 'monthly' } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.REPORT, name: 'Relatório de Repasses', description: 'Repasses a proprietários', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_arrecadado', 'total_descontos', 'total_repasses', 'pendentes'] }, { title: 'Por Proprietário', items: ['aluguel', 'descontos', 'liquido', 'status_repasse'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.REAL_ESTATE, type: TemplateType.INVOICE, name: 'NFS-e Locação', description: 'NFS-e para serviço de administração de imóveis', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.11', natureza: 'Administração de Imóveis', campos_adicionais: ['imovel', 'proprietario', 'inquilino'] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.INVOICE, name: 'Recibo de Aluguel', description: 'Layout de recibo de aluguel', isDefault: true, content: { formato: 'recibo', campos: ['inquilino', 'imovel', 'mes_referencia', 'valor_aluguel', 'descontos', 'multa_juros', 'total_pago', 'data_pagamento'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.REAL_ESTATE, type: TemplateType.PRODUCT_CATALOG, name: 'Tipos de Imóvel', description: 'Categorias de imóveis', isDefault: true, content: { categories: ['Apartamento', 'Casa', 'Comercial', 'Sala', 'Galpão', 'Terreno', 'Cobertura', 'Studio'] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Imobiliário', description: 'Unidades de medida para imóveis', isDefault: true, content: { units: [{ code: 'M2', name: 'Metro Quadrado' }, { code: 'UN', name: 'Unidade' }, { code: 'MENS', name: 'Mensalidade' }, { code: 'VAGA', name: 'Vaga de Garagem' }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Imobiliário', description: 'Margens por tipo de serviço', isDefault: false, content: { margins: [{ category: 'Administração Locação', margin: 0.80 }, { category: 'Comissão Venda', margin: 0.50 }, { category: 'Avaliação', margin: 0.70 }] } },
  // 2 ONBOARDING
  { niche: Niche.REAL_ESTATE, type: TemplateType.ONBOARDING, name: 'Setup Imobiliária', description: 'Configuração inicial para imobiliária', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Imobiliária', fields: ['cnpj', 'razao_social', 'creci'] }, { id: 2, title: 'Cadastrar Imóveis', action: 'import_properties' }, { id: 3, title: 'Cadastrar Proprietários', action: 'import_owners' }, { id: 4, title: 'Cadastrar Corretores', action: 'create_brokers' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.ONBOARDING, name: 'Migração de Portfólio', description: 'Migrar imóveis de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Imóveis', action: 'import_properties' }, { id: 3, title: 'Importar Contratos', action: 'import_contracts' }, { id: 4, title: 'Importar Financeiro', action: 'import_finance' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.REAL_ESTATE, type: TemplateType.NICHE_SPECIFIC, name: 'Vistoria de Imóvel', description: 'Checklist de vistoria de entrada/saída', isDefault: true, content: { rooms: ['sala', 'quartos', 'cozinha', 'banheiros', 'area_servico', 'garagem', 'area_externa'], fields: ['item', 'estado', 'observacao', 'foto'], rating_scale: [1, 2, 3, 4, 5] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.NICHE_SPECIFIC, name: 'Contrato de Locação', description: 'Template de contrato de locação residencial', isDefault: true, content: { sections: ['partes', 'imovel_objeto', 'valor_aluguel', 'reajuste', 'prazo', 'garantias', 'condominio', 'iptu', 'uso_imovel', 'reparos', 'rescisao', 'foro'] } },
  { niche: Niche.REAL_ESTATE, type: TemplateType.NICHE_SPECIFIC, name: 'Cálculo de Repasse', description: 'Template de cálculo de repasse ao proprietário', isDefault: false, content: { fields: ['aluguel_bruto', 'taxa_administracao_pct', 'condominio', 'iptu', 'seguro_incendio', 'manutencao', 'multas', 'repasse_liquido'] } },
];

// ─── AUTOMOTIVE ────────────────────────────────────────────────────────────
const AUTOMOTIVE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.AUTOMOTIVE, type: TemplateType.WORKFLOW, name: 'Cobrança de Serviço', description: 'Workflow de cobrança para oficina/auto', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar OS', trigger: 'service_completed', action: 'send_email', template: 'os-concluida' }, { id: 2, name: 'Lembrete Pagamento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-pagamento' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_5d', action: 'send_sms', template: 'atraso-pagamento' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Cadastro de novo cliente na oficina', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'customer_created', action: 'send_email', template: 'boas-vindas-oficina' }, { id: 2, name: 'Cadastro Veículo', trigger: 'timer_1d', action: 'send_email', template: 'cadastrar-veiculo' }, { id: 3, name: 'Lembrete Revisão', trigger: 'vehicle_due_maintenance', action: 'send_sms', template: 'revisao-proxima' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.WORKFLOW, name: 'Lembrete de Revisão', description: 'Alerta automático de revisão periódica', isDefault: true, content: { steps: [{ id: 1, name: 'Verificar KM', trigger: 'monthly_check', action: 'check_maintenance_schedule' }, { id: 2, name: 'Notificar Cliente', trigger: 'maintenance_due_15d', action: 'send_email', template: 'revisao-agendar' }, { id: 3, name: 'SMS 3d antes', trigger: 'maintenance_due_3d', action: 'send_sms', template: 'revisao-urgente' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.WORKFLOW, name: 'Ordem de Serviço', description: 'Fluxo de OS da entrada à entrega', isDefault: false, content: { steps: [{ id: 1, name: 'Receber Veículo', trigger: 'vehicle_received', action: 'create_os' }, { id: 2, name: 'Diagnóstico', trigger: 'os_created', action: 'notify', target: 'mechanic' }, { id: 3, name: 'Aprovar Orçamento', trigger: 'diagnosis_done', action: 'send_email', template: 'orcamento-aprovacao' }, { id: 4, name: 'Executar Serviço', trigger: 'budget_approved', action: 'start_service' }, { id: 5, name: 'Entregar', trigger: 'service_done', action: 'notify_customer' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.WORKFLOW, name: 'Controle de Peças', description: 'Gestão de estoque de peças e reposição', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Estoque', trigger: 'daily_check', action: 'check_parts_stock' }, { id: 2, name: 'Pedido Reposição', trigger: 'stock_below_min', action: 'create_purchase_order' }, { id: 3, name: 'Receber Peças', trigger: 'parts_received', action: 'update_stock' }] } },
  // 3 DASHBOARD
  { niche: Niche.AUTOMOTIVE, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira da oficina', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'parts_cost', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'avg_ticket', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'mechanic'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.DASHBOARD, name: 'Dashboard de Produção', description: 'OS, serviços e produtividade', isDefault: false, content: { widgets: [{ type: 'active_os', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'services_today', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'avg_service_time', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'by_mechanic', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'mechanic'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.DASHBOARD, name: 'Dashboard de Estoque', description: 'Peças e insumos', isDefault: false, content: { widgets: [{ type: 'total_parts', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'low_stock_alerts', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'top_parts_used', position: { x: 8, y: 0, w: 4, h: 4 } }], filters: ['category', 'supplier'] } },
  // 4 EMAIL
  { niche: Niche.AUTOMOTIVE, type: TemplateType.EMAIL, name: 'Boas-vindas Oficina', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nSeu cadastro foi realizado! Cadastre seu veículo para receber lembretes de revisão.\n\nAté breve!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.EMAIL, name: 'Orçamento Aprovação', description: 'Email com orçamento para aprovação', isDefault: true, content: { subject: 'Orçamento #{{os_number}} - {{vehicle_model}}', body: 'Olá {{customer_name}},\n\nOrçamento para {{vehicle_model}} ({{vehicle_plate}}):\n\n{{services_list}}\n{{parts_list}}\n\nTotal: R$ {{total_amount}}\n\nAprovar pelo link abaixo.', from: 'os@{{company_domain}}' } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.EMAIL, name: 'OS Concluída', description: 'Notificação de serviço concluído', isDefault: true, content: { subject: 'Seu veículo está pronto! - {{vehicle_model}}', body: 'Olá {{customer_name}},\n\nO serviço no {{vehicle_model}} ({{vehicle_plate}}) foi concluído.\n\nValor total: R$ {{total_amount}}\n\nVenha buscar!', from: 'os@{{company_domain}}' } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.EMAIL, name: 'Lembrete de Revisão', description: 'Email lembrando sobre revisão', isDefault: false, content: { subject: 'Hora da revisão do {{vehicle_model}}!', body: 'Olá {{customer_name}},\n\nSeu {{vehicle_model}} ({{vehicle_plate}}) está próximo do prazo de revisão.\n\nAgende pelo app ou ligue para {{phone}}.', from: 'contato@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.AUTOMOTIVE, type: TemplateType.REPORT, name: 'DRE Oficina', description: 'DRE para oficina mecânica', isDefault: true, content: { sections: [{ title: 'Receita', items: ['mao_obra', 'pecas', 'servicos_especiais'] }, { title: 'Custos', items: ['pecas_compradas', 'insumos', 'comissoes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'ferramentas', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.REPORT, name: 'Relatório de Produção', description: 'OS por mecânico e tipo de serviço', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_os', 'ticket_medio', 'tempo_medio_servico'] }, { title: 'Por Mecânico', items: ['os_por_mecanico', 'faturamento_por_mecanico'] }, { title: 'Por Tipo', items: ['revisao', 'reparo', 'pintura', 'eletrica', 'funilaria'] }], period: 'monthly' } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.REPORT, name: 'Relatório de Peças', description: 'Consumo e giro de peças', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_consumido', 'giro_estoque', 'pecas_mais_usadas'] }, { title: 'Por Fornecedor', items: ['compras_por_fornecedor', 'prazo_entrega'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.AUTOMOTIVE, type: TemplateType.INVOICE, name: 'NF-e Peças Automotivas', description: 'NF-e para venda de peças', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Peças Automotivas', campos_adicionais: ['veiculo', 'placa', 'os_numero'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.INVOICE, name: 'NFS-e Serviço Automotivo', description: 'NFS-e para serviço de oficina', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.10', natureza: 'Serviço de Manutenção Automotiva', campos_adicionais: ['veiculo', 'placa', 'os_numero', 'mecanico'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.AUTOMOTIVE, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias de Serviço', description: 'Categorias de serviços automotivos', isDefault: true, content: { categories: ['Revisão', 'Reparo Motor', 'Elétrica', 'Funilaria', 'Pintura', 'Suspensão', 'Freios', 'Ar Condicionado', 'Troca de Óleo', 'Lavagem'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Automotivo', description: 'Unidades de medida para oficina', isDefault: true, content: { units: [{ code: 'UN', name: 'Unidade' }, { code: 'H', name: 'Hora' }, { code: 'SV', name: 'Serviço' }, { code: 'L', name: 'Litro' }, { code: 'PCT', name: 'Kit' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Automotivo', description: 'Margens sugeridas por tipo de serviço', isDefault: false, content: { margins: [{ category: 'Mão de Obra', margin: 0.65 }, { category: 'Peças', margin: 0.40 }, { category: 'Revisão', margin: 0.55 }, { category: 'Funilaria/Pintura', margin: 0.50 }] } },
  // 2 ONBOARDING
  { niche: Niche.AUTOMOTIVE, type: TemplateType.ONBOARDING, name: 'Setup Oficina', description: 'Configuração inicial para oficina', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Oficina', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Cadastrar Mecânicos', action: 'create_mechanics' }, { id: 3, title: 'Cadastrar Serviços', action: 'create_services' }, { id: 4, title: 'Cadastrar Peças', action: 'import_parts' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Clientes', action: 'import_clients' }, { id: 3, title: 'Importar Veículos', action: 'import_vehicles' }, { id: 4, title: 'Importar Peças', action: 'import_parts' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.AUTOMOTIVE, type: TemplateType.NICHE_SPECIFIC, name: 'Ficha do Veículo', description: 'Cadastro completo de veículo do cliente', isDefault: true, content: { fields: ['marca', 'modelo', 'ano', 'cor', 'placa', 'renavam', 'chassi', 'combustivel', 'km_atual', 'tipo_oleo', 'ultima_revisao', 'proxima_revisao_km'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.NICHE_SPECIFIC, name: 'Ordem de Serviço', description: 'Template de OS para oficina', isDefault: true, content: { sections: ['dados_cliente', 'dados_veiculo', 'reclamacao', 'diagnostico', 'servicos_autorizados', 'pecas_utilizadas', 'valor_total', 'autorizacao_cliente'] } },
  { niche: Niche.AUTOMOTIVE, type: TemplateType.NICHE_SPECIFIC, name: 'Tabela de Revisão por Modelo', description: 'Intervalos de revisão por modelo de veículo', isDefault: false, content: { intervals: [{ km: 10000, services: ['troca_oleo', 'filtro_oleo'] }, { km: 20000, services: ['troca_oleo', 'filtro_oleo', 'filtro_ar', 'filtro_combustivel'] }, { km: 40000, services: ['troca_oleo', 'filtros', 'velas', 'freios', 'suspensao'] }] } },
];

// ─── AGRICULTURE ───────────────────────────────────────────────────────────
const AGRICULTURE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.AGRICULTURE, type: TemplateType.WORKFLOW, name: 'Cobrança de Safra', description: 'Workflow de cobrança para cooperativa/agro', isDefault: true, content: { steps: [{ id: 1, name: 'Nota de Entrega', trigger: 'delivery_confirmed', action: 'generate_invoice' }, { id: 2, name: 'Enviar Fatura', trigger: 'invoice_generated', action: 'send_email', template: 'fatura-safra' }, { id: 3, name: 'Lembrete 7d', trigger: 'invoice_due_7d', action: 'send_email', template: 'lembrete-pagamento' }, { id: 4, name: 'Aviso Atraso', trigger: 'invoice_overdue_15d', action: 'notify', target: 'manager' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.WORKFLOW, name: 'Onboarding de Produtor', description: 'Cadastro de novo produtor/cooperado', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'producer_created', action: 'send_email', template: 'boas-vindas-agro' }, { id: 2, name: 'Cadastrar Propriedade', trigger: 'timer_3d', action: 'send_email', template: 'cadastrar-propriedade' }, { id: 3, name: 'Acesso ao Portal', trigger: 'property_registered', action: 'create_access' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.WORKFLOW, name: 'Planejamento de Safra', description: 'Fluxo de planejamento safra', isDefault: true, content: { steps: [{ id: 1, name: 'Iniciar Planejamento', trigger: 'season_start_90d', action: 'notify', target: 'agronomist' }, { id: 2, name: 'Coletar Dados', trigger: 'notification_sent', action: 'request_field_data' }, { id: 3, name: 'Gerar Plano', trigger: 'data_collected', action: 'generate_plan' }, { id: 4, name: 'Aprovar Plano', trigger: 'plan_generated', action: 'notify', target: 'manager' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.WORKFLOW, name: 'Controle de Insumos', description: 'Gestão de compra e distribuição de insumos', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Estoque', trigger: 'monthly_check', action: 'check_inputs' }, { id: 2, name: 'Pedido Compra', trigger: 'stock_low', action: 'create_purchase_order' }, { id: 3, name: 'Distribuir', trigger: 'inputs_received', action: 'allocate_to_producers' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.WORKFLOW, name: 'Rastreabilidade', description: 'Fluxo de rastreabilidade de produção', isDefault: false, content: { steps: [{ id: 1, name: 'Registrar Plantio', trigger: 'planting_started', action: 'create_batch' }, { id: 2, name: 'Aplicação Insumos', trigger: 'input_applied', action: 'update_batch' }, { id: 3, name: 'Colheita', trigger: 'harvest_started', action: 'update_batch' }, { id: 4, name: 'Certificação', trigger: 'harvest_done', action: 'request_certification' }] } },
  // 3 DASHBOARD
  { niche: Niche.AGRICULTURE, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira do agronegócio', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'by_crop', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'cost_per_hectare', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'crop', 'property'] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.DASHBOARD, name: 'Dashboard de Safra', description: 'Acompanhamento de safra e produção', isDefault: false, content: { widgets: [{ type: 'planted_area', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'harvest_progress', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'productivity', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'by_property', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['season', 'crop', 'property'] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.DASHBOARD, name: 'Dashboard de Insumos', description: 'Controle de insumos e estoque', isDefault: false, content: { widgets: [{ type: 'total_inputs', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'by_type', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'stock_alerts', position: { x: 8, y: 0, w: 4, h: 4 } }], filters: ['period', 'crop'] } },
  // 4 EMAIL
  { niche: Niche.AGRICULTURE, type: TemplateType.EMAIL, name: 'Boas-vindas Cooperado', description: 'Email de boas-vindas para novo produtor', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{producer_name}},\n\nSeu cadastro foi realizado! Acesse o portal para cadastrar sua propriedade e acompanhar suas safras.\n\nBom trabalho!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.EMAIL, name: 'Fatura de Safra', description: 'Email com fatura de entrega de produção', isDefault: true, content: { subject: 'Fatura de entrega - {{crop_name}}', body: 'Olá {{producer_name}},\n\nReferente à entrega de {{crop_name}}:\nQuantidade: {{quantity}} {{unit}}\nValor: R$ {{amount}}\nVencimento: {{due_date}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.EMAIL, name: 'Alerta Climático', description: 'Email de alerta climático para produtores', isDefault: true, content: { subject: 'Alerta climático - {{region}}', body: 'Olá {{producer_name}},\n\nPrevisão para {{region}}:\n{{weather_forecast}}\n\nRecomendações: {{recommendations}}', from: 'tecnico@{{company_domain}}' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.EMAIL, name: 'Relatório de Safra', description: 'Relatório mensal de safra', isDefault: false, content: { subject: 'Relatório de safra - {{month}}', body: 'Olá {{producer_name}},\n\nResumo da safra:\n- Área plantada: {{area}} ha\n- Produção: {{production}} {{unit}}\n- Produtividade: {{productivity}} {{unit}}/ha\n- Custo/ha: R$ {{cost_per_hectare}}', from: 'tecnico@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.AGRICULTURE, type: TemplateType.REPORT, name: 'DRE Agronegócio', description: 'DRE para agronegócio/cooperativa', isDefault: true, content: { sections: [{ title: 'Receita', items: ['vendas_graos', 'vendas_insumos', 'prestacao_servicos'] }, { title: 'Custos', items: ['compra_graos', 'insumos', 'logistica', 'comissoes'] }, { title: 'Despesas', items: ['pessoal', 'manutencao', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.REPORT, name: 'Relatório de Safra', description: 'Análise de safra por cultura e propriedade', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['area_total', 'producao_total', 'produtividade_media'] }, { title: 'Por Cultura', items: ['soja', 'milho', 'cafe', 'cana', 'arroz'] }, { title: 'Por Propriedade', items: ['produtividade_propriedade', 'custo_propriedade'] }], period: 'seasonal' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.REPORT, name: 'Relatório de Insumos', description: 'Análise de consumo de insumos', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_consumido', 'custo_total', 'custo_por_hectare'] }, { title: 'Por Tipo', items: ['fertilizantes', 'defensivos', 'sementes', 'combustivel'] }, { title: 'Comparativo', items: ['consumo_vs_safra_anterior', 'custo_vs_safra_anterior'] }], period: 'seasonal' } },
  // 2 INVOICE
  { niche: Niche.AGRICULTURE, type: TemplateType.INVOICE, name: 'NF-e Grãos', description: 'NF-e para comercialização de grãos', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Produção Agrícola', campos_adicionais: ['safra', 'cultura', 'umidade', 'impurezas'] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.INVOICE, name: 'NFS-e Serviço Agrícola', description: 'NFS-e para serviço agrícola', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.12', natureza: 'Serviço Agrícola', campos_adicionais: ['propriedade', 'cultura', 'area_hectares'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.AGRICULTURE, type: TemplateType.PRODUCT_CATALOG, name: 'Culturas', description: 'Categorias de culturas agrícolas', isDefault: true, content: { categories: ['Soja', 'Milho', 'Café', 'Cana-de-Açúcar', 'Arroz', 'Feijão', 'Algodão', 'Trigo', 'Fruticultura', 'Pecuária'] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Agrícola', description: 'Unidades de medida para agricultura', isDefault: true, content: { units: [{ code: 'HA', name: 'Hectare' }, { code: 'KG', name: 'Quilograma' }, { code: 'T', name: 'Tonelada' }, { code: 'SAC', name: 'Saca 60kg' }, { code: 'L', name: 'Litro' }, { code: 'SC', name: 'Scoteiro' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Agrícola', description: 'Margens por cultura', isDefault: false, content: { margins: [{ category: 'Soja', margin: 0.25 }, { category: 'Milho', margin: 0.20 }, { category: 'Café', margin: 0.35 }, { category: 'Insumos', margin: 0.15 }] } },
  // 2 ONBOARDING
  { niche: Niche.AGRICULTURE, type: TemplateType.ONBOARDING, name: 'Setup Cooperativa', description: 'Configuração inicial para cooperativa/agro', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Cooperativa', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Cadastrar Produtores', action: 'import_producers' }, { id: 3, title: 'Cadastrar Propriedades', action: 'import_properties' }, { id: 4, title: 'Configurar Culturas', action: 'setup_crops' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.AGRICULTURE, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar de outro sistema agro', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Produtores', action: 'import_producers' }, { id: 3, title: 'Importar Propriedades', action: 'import_properties' }, { id: 4, title: 'Importar Financeiro', action: 'import_finance' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.AGRICULTURE, type: TemplateType.NICHE_SPECIFIC, name: 'Caderno de Campo', description: 'Registro de atividades de campo', isDefault: true, content: { fields: ['data', 'propriedade', 'talhao', 'atividade', 'insumo_utilizado', 'quantidade', 'condicoes_clima', 'observacoes'], geo_tagging: true } },
  { niche: Niche.AGRICULTURE, type: TemplateType.NICHE_SPECIFIC, name: 'Custo de Produção por Hectare', description: 'Cálculo de custo de produção detalhado', isDefault: true, content: { categories: ['insumos', 'sementes', 'defensivos', 'fertilizantes', 'combustivel', 'mao_obra', 'maquinas', 'impostos', 'arrendamento', 'custo_fixo'], output: 'custo_total_hectare', productivity_unit: 'sacas_ha' } },
  { niche: Niche.AGRICULTURE, type: TemplateType.NICHE_SPECIFIC, name: 'Integração Clima', description: 'Configuração de integração com dados meteorológicos', isDefault: false, content: { providers: ['inmet', 'cptec', 'wather_api'], alert_types: ['geada', 'seca', 'chuva_excessiva', 'vento_forte'], auto_notify: true } },
];

export { TECH_SERVICES_TEMPLATES, REAL_ESTATE_TEMPLATES, AUTOMOTIVE_TEMPLATES, AGRICULTURE_TEMPLATES };
