import { Niche, TemplateType } from '@prisma/client';

interface TemplateSeed {
  niche: Niche;
  type: TemplateType;
  name: string;
  description: string;
  content: Record<string, any>;
  isDefault: boolean;
}

// ─── BEAUTY ────────────────────────────────────────────────────────────────
const BEAUTY_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.BEAUTY, type: TemplateType.WORKFLOW, name: 'Cobrança de Serviço', description: 'Workflow de cobrança para salão de beleza', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Fatura', trigger: 'service_completed', action: 'send_email', template: 'fatura-salao' }, { id: 2, name: 'Lembrete 3 dias', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-pagamento' }, { id: 3, name: 'SMS Atraso', trigger: 'invoice_overdue_3d', action: 'send_sms', template: 'sms-atraso' }, { id: 4, name: 'Bloquear Agendamento', trigger: 'invoice_overdue_15d', action: 'block_booking' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.WORKFLOW, name: 'Onboarding Cliente', description: 'Boas-vindas para nova cliente do salão', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'customer_created', action: 'send_email', template: 'boas-vindas-beleza' }, { id: 2, name: 'Cupom Primeira Visita', trigger: 'timer_1d', action: 'send_email', template: 'cupom-primeira-visita' }, { id: 3, name: 'Lembrete Retorno', trigger: 'first_visit_14d', action: 'send_sms', template: 'retorno-beleza' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.WORKFLOW, name: 'Lembrete de Agendamento', description: 'Confirmação e lembrete de horário', isDefault: true, content: { steps: [{ id: 1, name: 'Confirmar 24h', trigger: 'appointment_24h', action: 'send_sms', template: 'confirmar-horario' }, { id: 2, name: 'Lembrete 2h', trigger: 'appointment_2h', action: 'send_sms', template: 'lembrete-2h-beleza' }, { id: 3, name: 'No-show', trigger: 'appointment_missed', action: 'mark_no_show' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.WORKFLOW, name: 'Controle de Estoque Produto', description: 'Alerta de reposição de produtos de beleza', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Estoque', trigger: 'daily_check', action: 'check_stock', threshold: 5 }, { id: 2, name: 'Alerta Gestora', trigger: 'stock_low', action: 'notify', target: 'manager' }, { id: 3, name: 'Gerar Pedido', trigger: 'stock_critical', action: 'create_purchase_order' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.WORKFLOW, name: 'Follow-up Pós-Procedimento', description: 'Acompanhamento após procedimento estético', isDefault: false, content: { steps: [{ id: 1, name: 'Cuidados 24h', trigger: 'procedure_done_1d', action: 'send_email', template: 'cuidados-pos-procedimento' }, { id: 2, name: 'NPS 7d', trigger: 'timer_7d', action: 'send_email', template: 'nps-beleza' }, { id: 3, name: 'Oferta Retorno', trigger: 'timer_30d', action: 'send_sms', template: 'oferta-retorno' }] } },
  // 3 DASHBOARD
  { niche: Niche.BEAUTY, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira do salão', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'commissions', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'avg_ticket', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'professional'] } },
  { niche: Niche.BEAUTY, type: TemplateType.DASHBOARD, name: 'Dashboard de Agenda', description: 'Ocupação e horários do salão', isDefault: false, content: { widgets: [{ type: 'today_schedule', position: { x: 0, y: 0, w: 6, h: 6 } }, { type: 'occupancy_rate', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'no_show_rate', position: { x: 6, y: 4, w: 6, h: 2 } }], filters: ['professional', 'date'] } },
  { niche: Niche.BEAUTY, type: TemplateType.DASHBOARD, name: 'Dashboard de Produtos', description: 'Vendas de produtos e estoque', isDefault: false, content: { widgets: [{ type: 'product_sales', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'stock_alerts', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'top_products', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'brand'] } },
  // 4 EMAIL
  { niche: Niche.BEAUTY, type: TemplateType.EMAIL, name: 'Boas-vindas Salão', description: 'Email de boas-vindas para nova cliente', isDefault: true, content: { subject: 'Bem-vinda à {{company_name}}!', body: 'Olá {{customer_name}},\n\nQue bom ter você conosco! Aproveite 15% OFF na primeira visita com o cupom BELEZA15.\n\nTe esperamos!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.BEAUTY, type: TemplateType.EMAIL, name: 'Confirmação de Horário', description: 'Email de confirmação de agendamento', isDefault: true, content: { subject: 'Horário confirmado - {{date}} às {{time}}', body: 'Olá {{customer_name}},\n\nSeu horário está confirmado:\nData: {{date}}\nHora: {{time}}\nProfissional: {{professional_name}}\nServiço: {{service_name}}\n\nCancelamentos com 6h de antecedência.', from: 'agenda@{{company_domain}}' } },
  { niche: Niche.BEAUTY, type: TemplateType.EMAIL, name: 'Cobrança Serviço', description: 'Email de cobrança para serviços realizados', isDefault: true, content: { subject: 'Fatura - {{company_name}}', body: 'Olá {{customer_name}},\n\nServiço: {{service_name}}\nValor: R$ {{amount}}\nVencimento: {{due_date}}\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.BEAUTY, type: TemplateType.EMAIL, name: 'Promoção do Mês', description: 'Email com promoções mensais', isDefault: false, content: { subject: 'Promoções do mês na {{company_name}}!', body: 'Olá {{customer_name}},\n\nConfira nossas promoções:\n{{promotions_list}}\n\nAgende já!', from: 'marketing@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.BEAUTY, type: TemplateType.REPORT, name: 'DRE Salão', description: 'DRE para salão de beleza', isDefault: true, content: { sections: [{ title: 'Receita', items: ['servicos', 'vendas_produtos', 'pacotes', 'assinaturas'] }, { title: 'Custos', items: ['produtos_usados', 'comissoes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'produtos_estoque', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.BEAUTY, type: TemplateType.REPORT, name: 'Relatório de Produção', description: 'Produção por profissional e serviço', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_atendimentos', 'ticket_medio', 'taxa_retorno'] }, { title: 'Por Profissional', items: ['atendimentos_por_profissional', 'faturamento_por_profissional', 'comissoes'] }, { title: 'Por Serviço', items: ['servicos_mais_procurados', 'ticket_medio_servico'] }], period: 'monthly' } },
  { niche: Niche.BEAUTY, type: TemplateType.REPORT, name: 'Relatório de Vendas de Produto', description: 'Análise de vendas de produtos no salão', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_vendido', 'margem_media', 'produtos_mais_vendidos'] }, { title: 'Por Marca', items: ['vendas_por_marca', 'margem_por_marca'] }, { title: 'Estoque', items: ['giro_estoque', 'produtos_parados'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.BEAUTY, type: TemplateType.INVOICE, name: 'NFS-e Salão', description: 'NFS-e para serviços de beleza', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.06', natureza: 'Serviço de Beleza', campos_adicionais: ['profissional', 'servico'] } },
  { niche: Niche.BEAUTY, type: TemplateType.INVOICE, name: 'NF-e Produto Beleza', description: 'NF-e para venda de produtos de beleza', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Produto de Beleza', campos_adicionais: [] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.BEAUTY, type: TemplateType.PRODUCT_CATALOG, name: 'Serviços de Beleza', description: 'Categorias de serviços do salão', isDefault: true, content: { categories: ['Corte', 'Coloração', 'Hidratação', 'Manicure', 'Pedicure', 'Estética Facial', 'Estética Corporal', 'Depilação', 'Maquiagem', 'Pacotes'] } },
  { niche: Niche.BEAUTY, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Beleza', description: 'Unidades de medida para salão', isDefault: true, content: { units: [{ code: 'UN', name: 'Unidade' }, { code: 'SESS', name: 'Sessão' }, { code: 'PCT', name: 'Pacote' }, { code: 'ML', name: 'Mililitro' }, { code: 'G', name: 'Grama' }, { code: 'MENS', name: 'Mensalidade' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Beleza', description: 'Margens sugeridas por serviço', isDefault: false, content: { margins: [{ category: 'Corte', margin: 0.70 }, { category: 'Coloração', margin: 0.55 }, { category: 'Estética', margin: 0.60 }, { category: 'Produtos', margin: 0.45 }, { category: 'Pacotes', margin: 0.50 }] } },
  // 2 ONBOARDING
  { niche: Niche.BEAUTY, type: TemplateType.ONBOARDING, name: 'Setup Salão', description: 'Configuração inicial para salão de beleza', isDefault: true, content: { steps: [{ id: 1, title: 'Dados do Salão', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Cadastrar Profissionais', action: 'create_professionals' }, { id: 3, title: 'Cadastrar Serviços', action: 'create_services' }, { id: 4, title: 'Configurar Agenda', action: 'setup_schedule' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.BEAUTY, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar de outro sistema de salão', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Clientes', action: 'import_clients' }, { id: 3, title: 'Importar Serviços', action: 'import_services' }, { id: 4, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.BEAUTY, type: TemplateType.NICHE_SPECIFIC, name: 'Ficha de Anamnese Estética', description: 'Ficha de anamnese para procedimentos estéticos', isDefault: true, content: { fields: ['alergias', 'medicamentos', 'historico_dermatologico', 'tipo_pele', 'procedimentos_anteriores', 'contraindicacoes'] } },
  { niche: Niche.BEAUTY, type: TemplateType.NICHE_SPECIFIC, name: 'Comissão de Profissional', description: 'Regras de comissão por profissional e serviço', isDefault: true, content: { rules: { type: 'percentage', default_pct: 40, by_service: { 'Corte': 50, 'Coloração': 35, 'Estética': 30 }, product_sales_pct: 10 } } },
  { niche: Niche.BEAUTY, type: TemplateType.NICHE_SPECIFIC, name: 'Programa Fidelidade Beleza', description: 'Programa de pontos para salão', isDefault: false, content: { rules: { points_per_real: 1, minimum_purchase: 30, expiration_days: 120, rewards: [{ points: 200, reward: 'Corte grátis' }, { points: 500, reward: 'Hidratação grátis' }] } } },
];

// ─── FITNESS ───────────────────────────────────────────────────────────────
const FITNESS_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.FITNESS, type: TemplateType.WORKFLOW, name: 'Cobrança de Mensalidade', description: 'Workflow de cobrança para academias', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Boleto', trigger: 'invoice_5d_before_due', action: 'send_email', template: 'boleto-mensalidade-fitness' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_date', action: 'send_sms', template: 'vencimento-hoje-fitness' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_3d', action: 'send_email', template: 'mensalidade-atrasada' }, { id: 4, name: 'Bloquear Catraca', trigger: 'invoice_overdue_15d', action: 'block_access' }] } },
  { niche: Niche.FITNESS, type: TemplateType.WORKFLOW, name: 'Onboarding Aluno', description: 'Boas-vindas para novo aluno da academia', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'student_created', action: 'send_email', template: 'boas-vindas-fitness' }, { id: 2, name: 'Avaliação Física', trigger: 'timer_3d', action: 'schedule_assessment' }, { id: 3, name: 'Treino Personalizado', trigger: 'assessment_done', action: 'send_email', template: 'treino-disponivel' }] } },
  { niche: Niche.FITNESS, type: TemplateType.WORKFLOW, name: 'Reativação Aluno Inativo', description: 'Fluxo para alunos que pararam de treinar', isDefault: true, content: { steps: [{ id: 1, name: 'Detectar Inatividade', trigger: 'no_checkin_15d', action: 'send_email', template: 'saudades-de-voce' }, { id: 2, name: 'SMS Motivacional', trigger: 'timer_7d', action: 'send_sms', template: 'volta-pra-academia' }, { id: 3, name: 'Oferta Especial', trigger: 'timer_14d', action: 'send_email', template: 'oferta-reativacao' }] } },
  { niche: Niche.FITNESS, type: TemplateType.WORKFLOW, name: 'Lembrete de Avaliação', description: 'Lembrete para avaliação física periódica', isDefault: false, content: { steps: [{ id: 1, name: 'Lembrete 30d', trigger: 'assessment_due_30d', action: 'send_email', template: 'avaliacao-proxima' }, { id: 2, name: 'Agendar', trigger: 'timer_7d', action: 'send_sms', template: 'agende-avaliacao' }] } },
  { niche: Niche.FITNESS, type: TemplateType.WORKFLOW, name: 'Renovação de Plano', description: 'Fluxo de renovação de plano anual', isDefault: false, content: { steps: [{ id: 1, name: 'Alerta 30d', trigger: 'plan_expires_30d', action: 'send_email', template: 'renovacao-plano' }, { id: 2, name: 'Oferta Anual', trigger: 'timer_15d', action: 'send_email', template: 'oferta-anual' }, { id: 3, name: 'Follow-up', trigger: 'timer_7d', action: 'send_sms', template: 'ultima-chance-renovacao' }] } },
  // 3 DASHBOARD
  { niche: Niche.FITNESS, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira da academia', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'active_members', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'churn_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'unit'] } },
  { niche: Niche.FITNESS, type: TemplateType.DASHBOARD, name: 'Dashboard de Alunos', description: 'Métricas de alunos e retenção', isDefault: false, content: { widgets: [{ type: 'active_students', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'attendance_trend', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'retention_rate', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'peak_hours', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'unit'] } },
  { niche: Niche.FITNESS, type: TemplateType.DASHBOARD, name: 'Dashboard de Inadimplência', description: 'Acompanhamento de mensalidades em atraso', isDefault: false, content: { widgets: [{ type: 'total_overdue', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'aging_chart', position: { x: 4, y: 0, w: 8, h: 4 } }, { type: 'blocked_access', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period'] } },
  // 4 EMAIL
  { niche: Niche.FITNESS, type: TemplateType.EMAIL, name: 'Boas-vindas Academia', description: 'Email de boas-vindas para novo aluno', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{student_name}},\n\nSua matrícula está ativa! Sua avaliação física está agendada.\n\nAcesse o app para verificar treinos e horários.\n\nBora treinar!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.FITNESS, type: TemplateType.EMAIL, name: 'Boleto Mensalidade', description: 'Email com boleto da mensalidade', isDefault: true, content: { subject: 'Mensalidade {{month}} - {{company_name}}', body: 'Olá {{student_name}},\n\nMensalidade de {{month}}: R$ {{amount}}\nVencimento: {{due_date}}\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.FITNESS, type: TemplateType.EMAIL, name: 'Reativação', description: 'Email motivacional para aluno inativo', isDefault: true, content: { subject: 'Sentimos sua falta, {{student_name}}!', body: 'Olá {{student_name}},\n\nFaz {{days_inactive}} dias que não te vemos por aqui.\n\nQue tal voltar? Preparamos uma condição especial para você!\n\nTe esperamos!', from: 'relacionamento@{{company_domain}}' } },
  { niche: Niche.FITNESS, type: TemplateType.EMAIL, name: 'Treino Disponível', description: 'Notificação de novo treino disponível', isDefault: false, content: { subject: 'Novo treino disponível!', body: 'Olá {{student_name}},\n\nSeu novo treino já está disponível no app.\n\nConsulte seu professor para dúvidas.', from: 'treino@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.FITNESS, type: TemplateType.REPORT, name: 'DRE Academia', description: 'DRE para academia', isDefault: true, content: { sections: [{ title: 'Receita', items: ['mensalidades', 'personal', 'loja', 'bar'] }, { title: 'Custos', items: ['equipamentos', 'manutencao', 'comissoes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'energia', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.FITNESS, type: TemplateType.REPORT, name: 'Relatório de Alunos', description: 'Análise de base de alunos e retenção', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_ativos', 'novos_mes', 'cancelamentos', 'churn_rate'] }, { title: 'Frequência', items: ['checkins_dia', 'horarios_pico', 'frequencia_media'] }, { title: 'Planos', items: ['distribuicao_planos', 'ticket_medio'] }], period: 'monthly' } },
  { niche: Niche.FITNESS, type: TemplateType.REPORT, name: 'Relatório de Personal', description: 'Produção e comissões de personal trainers', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_personals', 'alunos_por_personal', 'faturamento_personal'] }, { title: 'Por Profissional', items: ['sessoes_mes', 'comissoes', 'avaliacao_alunos'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.FITNESS, type: TemplateType.INVOICE, name: 'NFS-e Academia', description: 'NFS-e para serviços de academia', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.09', natureza: 'Serviço de Atividade Física', campos_adicionais: ['plano', 'aluno'] } },
  { niche: Niche.FITNESS, type: TemplateType.INVOICE, name: 'Boleto Mensalidade Fitness', description: 'Layout de boleto para mensalidade', isDefault: true, content: { formato: 'boleto', campos: ['nosso_numero', 'valor', 'vencimento', 'aluno', 'plano', 'mes_referencia'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.FITNESS, type: TemplateType.PRODUCT_CATALOG, name: 'Planos e Serviços', description: 'Categorias de planos de academia', isDefault: true, content: { categories: ['Mensal', 'Trimestral', 'Semestral', 'Anual', 'Personal', 'Grupos', 'Modalidades', 'Loja'] } },
  { niche: Niche.FITNESS, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Fitness', description: 'Unidades de medida para academia', isDefault: true, content: { units: [{ code: 'MENS', name: 'Mensalidade' }, { code: 'SESS', name: 'Sessão' }, { code: 'UN', name: 'Unidade' }, { code: 'H', name: 'Hora' }, { code: 'PCT', name: 'Pacote' }] } },
  { niche: Niche.FITNESS, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Fitness', description: 'Margens por tipo de plano', isDefault: false, content: { margins: [{ category: 'Mensal', margin: 0.40 }, { category: 'Anual', margin: 0.55 }, { category: 'Personal', margin: 0.35 }, { category: 'Loja', margin: 0.45 }] } },
  // 2 ONBOARDING
  { niche: Niche.FITNESS, type: TemplateType.ONBOARDING, name: 'Setup Academia', description: 'Configuração inicial para academia', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Academia', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Cadastrar Planos', action: 'create_plans' }, { id: 3, title: 'Cadastrar Professores', action: 'create_trainers' }, { id: 4, title: 'Configurar Catraca', action: 'setup_access' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.FITNESS, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar de outro sistema de academia', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Alunos', action: 'import_students' }, { id: 3, title: 'Importar Financeiro', action: 'import_finance' }, { id: 4, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.FITNESS, type: TemplateType.NICHE_SPECIFIC, name: 'Ficha de Avaliação Física', description: 'Template de avaliação física completa', isDefault: true, content: { fields: ['peso', 'altura', 'imc', 'gordura_corporal', 'massa_magra', 'cintura', 'quadril', 'rcq', 'flexibilidade', 'forca', 'resistencia', 'observacoes'] } },
  { niche: Niche.FITNESS, type: TemplateType.NICHE_SPECIFIC, name: 'Controle de Catraca', description: 'Integração com sistema de catraca/accesso', isDefault: true, content: { providers: ['tuasaude', 'linx', 'totvs', 'smartfit'], checkin_fields: ['aluno_id', 'data_hora', 'catraca_id'], auto_block_overdue: true } },
  { niche: Niche.FITNESS, type: TemplateType.NICHE_SPECIFIC, name: 'Controle de Horários de Pico', description: 'Gestão de fluxo por horário', isDefault: false, content: { peak_hours: [{ day: 'segunda-feira', start: '18:00', end: '20:00' }, { day: 'quarta-feira', start: '18:00', end: '20:00' }], capacity_limit: 50, waitlist_enabled: true } },
];

// ─── LEGAL ─────────────────────────────────────────────────────────────────
const LEGAL_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.LEGAL, type: TemplateType.WORKFLOW, name: 'Cobrança de Honorários', description: 'Workflow de cobrança para escritório jurídico', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Fatura', trigger: 'invoice_created', action: 'send_email', template: 'fatura-honorarios-juridico' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-vencimento' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_5d', action: 'send_email', template: 'aviso-atraso-honorarios' }, { id: 4, name: 'Notificar Sócio', trigger: 'invoice_overdue_15d', action: 'notify', target: 'partner' }] } },
  { niche: Niche.LEGAL, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Cadastro e boas-vindas para novo cliente', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'client_created', action: 'send_email', template: 'boas-vindas-juridico' }, { id: 2, name: 'Procuração', trigger: 'timer_1d', action: 'send_email', template: 'procuracao-modelo' }, { id: 3, name: 'Contrato de Honorários', trigger: 'timer_3d', action: 'send_email', template: 'contrato-honorarios' }] } },
  { niche: Niche.LEGAL, type: TemplateType.WORKFLOW, name: 'Prazo Processual', description: 'Alerta automático de prazos processuais', isDefault: true, content: { steps: [{ id: 1, name: 'Alerta 7d', trigger: 'deadline_7d', action: 'notify', target: 'responsible_lawyer' }, { id: 2, name: 'Alerta 3d', trigger: 'deadline_3d', action: 'send_email', template: 'prazo-urgente' }, { id: 3, name: 'Alerta 1d', trigger: 'deadline_1d', action: 'send_sms', template: 'prazo-critico' }] } },
  { niche: Niche.LEGAL, type: TemplateType.WORKFLOW, name: 'Andamento Processual', description: 'Atualização automática de andamentos', isDefault: false, content: { steps: [{ id: 1, name: 'Consultar Diário', trigger: 'daily_check', action: 'check_dje' }, { id: 2, name: 'Notificar Advogado', trigger: 'new_development', action: 'notify', target: 'responsible_lawyer' }, { id: 3, name: 'Atualizar Cliente', trigger: 'development_confirmed', action: 'send_email', template: 'andamento-processo' }] } },
  { niche: Niche.LEGAL, type: TemplateType.WORKFLOW, name: 'Follow-up Pós-Audiência', description: 'Acompanhamento após audiência', isDefault: false, content: { steps: [{ id: 1, name: 'Resumo Audiência', trigger: 'hearing_completed', action: 'send_email', template: 'resumo-audiencia' }, { id: 2, name: 'Próximos Passos', trigger: 'timer_2d', action: 'create_task' }, { id: 3, name: 'Atualizar Cliente', trigger: 'timer_5d', action: 'send_email', template: 'atualizacao-pos-audiencia' }] } },
  // 3 DASHBOARD
  { niche: Niche.LEGAL, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira do escritório', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'avg_hourly_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'area'] } },
  { niche: Niche.LEGAL, type: TemplateType.DASHBOARD, name: 'Dashboard Processual', description: 'Acompanhamento de processos e prazos', isDefault: false, content: { widgets: [{ type: 'active_cases', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'upcoming_deadlines', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'cases_by_area', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'cases_by_status', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['area', 'status', 'responsible'] } },
  { niche: Niche.LEGAL, type: TemplateType.DASHBOARD, name: 'Dashboard de Produtividade', description: 'Horas e tarefas por advogado', isDefault: false, content: { widgets: [{ type: 'hours_by_lawyer', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'tasks_overview', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'billable_vs_non', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'lawyer'] } },
  // 4 EMAIL
  { niche: Niche.LEGAL, type: TemplateType.EMAIL, name: 'Boas-vindas Escritório', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) ao escritório {{company_name}}', body: 'Olá {{client_name}},\n\nSeu caso está sob responsabilidade do Dr(a). {{lawyer_name}}.\n\nEstamos à disposição para qualquer dúvida.', from: 'contato@{{company_domain}}' } },
  { niche: Niche.LEGAL, type: TemplateType.EMAIL, name: 'Fatura de Honorários', description: 'Email com fatura de honorários', isDefault: true, content: { subject: 'Fatura de honorários #{{invoice_number}}', body: 'Olá {{client_name}},\n\nReferente aos serviços do mês:\nValor: R$ {{amount}}\nVencimento: {{due_date}}\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.LEGAL, type: TemplateType.EMAIL, name: 'Andamento de Processo', description: 'Atualização sobre andamento processual', isDefault: true, content: { subject: 'Atualização do processo {{case_number}}', body: 'Olá {{client_name}},\n\nNovo andamento no processo {{case_number}}:\n{{development_description}}\n\nPróximos passos: {{next_steps}}', from: 'processos@{{company_domain}}' } },
  { niche: Niche.LEGAL, type: TemplateType.EMAIL, name: 'Relatório Mensal de Casos', description: 'Resumo mensal de atividades', isDefault: false, content: { subject: 'Relatório mensal - {{month}}/{{year}}', body: 'Olá {{client_name}},\n\nResumo do mês:\n- Horas trabalhadas: {{hours}}\n- Andamentos: {{developments}}\n- Próximos prazos: {{deadlines}}\n\nDúvidas? Entre em contato.', from: 'contato@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.LEGAL, type: TemplateType.REPORT, name: 'DRE Jurídico', description: 'DRE para escritório de advocacia', isDefault: true, content: { sections: [{ title: 'Receita', items: ['honorarios', 'exitos', 'consultas', 'recorrentes'] }, { title: 'Custos', items: ['estagiarios', 'correspondentes', 'procuracoes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'assessorias', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.LEGAL, type: TemplateType.REPORT, name: 'Relatório de Horas', description: 'Tracking de horas por advogado e caso', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_horas', 'horas_faturaveis', 'taxa_aproveitamento'] }, { title: 'Por Advogado', items: ['horas_por_advogado', 'faturamento_por_advogado'] }, { title: 'Por Caso', items: ['horas_por_caso', 'budget_vs_real'] }], period: 'monthly' } },
  { niche: Niche.LEGAL, type: TemplateType.REPORT, name: 'Relatório de Processos', description: 'Análise de carteira de processos', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_ativos', 'novos_mes', 'encerrados', 'em_andamento'] }, { title: 'Por Área', items: ['civel', 'trabalhista', 'criminal', 'tributario'] }, { title: 'Prazos', items: ['prazos_proximos_30d', 'prazos_vencidos'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.LEGAL, type: TemplateType.INVOICE, name: 'NFS-e Advocacia', description: 'NFS-e para serviços jurídicos', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.03', natureza: 'Serviço de Advocacia', campos_adicionais: ['oab_advogado', 'numero_processo', 'cliente'] } },
  { niche: Niche.LEGAL, type: TemplateType.INVOICE, name: 'Fatura de Honorários Jurídico', description: 'Layout de fatura de honorários', isDefault: true, content: { formato: 'fatura', campos: ['cliente', 'processo', 'periodo', 'horas', 'valor_hora', 'total', 'impostos', 'liquido', 'pix'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.LEGAL, type: TemplateType.PRODUCT_CATALOG, name: 'Áreas de Atuação', description: 'Categorias de serviços jurídicos', isDefault: true, content: { categories: ['Direito Civil', 'Direito Trabalhista', 'Direito Criminal', 'Direito Tributário', 'Direito Empresarial', 'Direito Imobiliário', 'Direito de Família', 'Direito Digital'] } },
  { niche: Niche.LEGAL, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Jurídico', description: 'Unidades de medida para serviços jurídicos', isDefault: true, content: { units: [{ code: 'H', name: 'Hora' }, { code: 'CASO', name: 'Caso/Processo' }, { code: 'MENS', name: 'Mensalidade' }, { code: 'CONS', name: 'Consulta' }, { code: 'AUD', name: 'Audiência' }] } },
  { niche: Niche.LEGAL, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Jurídico', description: 'Margens sugeridas por área', isDefault: false, content: { margins: [{ category: 'Consultoria', margin: 0.65 }, { category: 'Processos', margin: 0.50 }, { category: 'Recorrentes', margin: 0.70 }] } },
  // 2 ONBOARDING
  { niche: Niche.LEGAL, type: TemplateType.ONBOARDING, name: 'Setup Escritório', description: 'Configuração inicial para escritório jurídico', isDefault: true, content: { steps: [{ id: 1, title: 'Dados do Escritório', fields: ['cnpj', 'razao_social', 'oab'] }, { id: 2, title: 'Cadastrar Advogados', action: 'create_lawyers', fields: ['oab', 'area'] }, { id: 3, title: 'Cadastrar Clientes', action: 'import_clients' }, { id: 4, title: 'Configurar Prazos', action: 'setup_deadlines' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.LEGAL, type: TemplateType.ONBOARDING, name: 'Migração de Processos', description: 'Migrar dados de outro sistema jurídico', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Processos', action: 'import_cases' }, { id: 3, title: 'Importar Clientes', action: 'import_clients' }, { id: 4, title: 'Importar Financeiro', action: 'import_finance' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.LEGAL, type: TemplateType.NICHE_SPECIFIC, name: 'Controle de Prazos', description: 'Sistema de controle de prazos processuais', isDefault: true, content: { sources: ['diario_oficial', 'sistemas_trf', 'push_sistema'], alert_levels: [{ days: 7, level: 'info' }, { days: 3, level: 'warning' }, { days: 1, level: 'critical' }], auto_push: true } },
  { niche: Niche.LEGAL, type: TemplateType.NICHE_SPECIFIC, name: 'Timesheet Jurídico', description: 'Registro de horas por processo', isDefault: true, content: { fields: ['data', 'processo', 'cliente', 'advogado', 'atividade', 'horas', 'descricao', 'faturavel'], approval_flow: true, minimum_interval_min: 6 } },
  { niche: Niche.LEGAL, type: TemplateType.NICHE_SPECIFIC, name: 'Contrato de Honorários', description: 'Template de contrato de honorários advocatícios', isDefault: false, content: { sections: ['partes', 'objeto', 'honorarios_fixos', 'honorarios_sucesso', 'custas', 'forma_pagamento', 'rescisao', 'foro'] } },
];

// ─── ACCOUNTING ────────────────────────────────────────────────────────────
const ACCOUNTING_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.ACCOUNTING, type: TemplateType.WORKFLOW, name: 'Cobrança de Mensalidade', description: 'Workflow de cobrança para escritório contábil', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Fatura', trigger: 'invoice_5d_before_due', action: 'send_email', template: 'fatura-mensalidade-contabil' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_date', action: 'send_sms', template: 'vencimento-hoje' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_3d', action: 'send_email', template: 'atraso-mensalidade' }, { id: 4, name: 'Suspender Serviço', trigger: 'invoice_overdue_30d', action: 'suspend_service' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Cadastro de novo cliente contábil', isDefault: true, content: { steps: [{ id: 1, name: 'Boas-vindas', trigger: 'client_created', action: 'send_email', template: 'boas-vindas-contabil' }, { id: 2, name: 'Documentos Necessários', trigger: 'timer_1d', action: 'send_email', template: 'documentos-necessarios' }, { id: 3, name: 'Acesso ao Portal', trigger: 'documents_received', action: 'create_access' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.WORKFLOW, name: 'Obrigações Fiscais', description: 'Alerta de obrigações acessórias', isDefault: true, content: { steps: [{ id: 1, name: 'Alerta 15d', trigger: 'obligation_due_15d', action: 'notify', target: 'accountant' }, { id: 2, name: 'Solicitar Documentos', trigger: 'obligation_due_10d', action: 'send_email', template: 'solicitar-documentos' }, { id: 3, name: 'Prazo Crítico', trigger: 'obligation_due_3d', action: 'send_sms', template: 'prazo-critico-fiscal' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.WORKFLOW, name: 'Entrega de Documentos', description: 'Fluxo de entrega de documentos pelo cliente', isDefault: false, content: { steps: [{ id: 1, name: 'Solicitar Docs', trigger: 'monthly_cycle', action: 'send_email', template: 'solicitar-docs-mes' }, { id: 2, name: 'Lembrete 5d', trigger: 'timer_5d', action: 'send_sms', template: 'docs-pendentes' }, { id: 3, name: 'Urgência', trigger: 'timer_10d', action: 'send_email', template: 'docs-urgencia' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.WORKFLOW, name: 'Fechamento Mensal', description: 'Processo de fechamento contábil mensal', isDefault: false, content: { steps: [{ id: 1, name: 'Receber Documentos', trigger: 'month_start', action: 'check_documents' }, { id: 2, name: 'Conciliação', trigger: 'documents_ok', action: 'create_task', type: 'reconciliation' }, { id: 3, name: 'Escriturar', trigger: 'reconciliation_done', action: 'create_task', type: 'bookkeeping' }, { id: 4, name: 'Enviar Obrigações', trigger: 'bookkeeping_done', action: 'send_obligations' }] } },
  // 3 DASHBOARD
  { niche: Niche.ACCOUNTING, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira do escritório contábil', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'active_clients', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'accountant'] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.DASHBOARD, name: 'Dashboard de Obrigações', description: 'Calendário fiscal e obrigações', isDefault: false, content: { widgets: [{ type: 'calendar_fiscal', position: { x: 0, y: 0, w: 8, h: 6 } }, { type: 'pending_obligations', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'overdue_obligations', position: { x: 8, y: 4, w: 4, h: 2 } }], filters: ['month', 'client'] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.DASHBOARD, name: 'Dashboard de Clientes', description: 'Análise da carteira de clientes', isDefault: false, content: { widgets: [{ type: 'total_clients', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'by_regime', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'by_activity', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'churn', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period'] } },
  // 4 EMAIL
  { niche: Niche.ACCOUNTING, type: TemplateType.EMAIL, name: 'Boas-vindas Contábil', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) ao escritório {{company_name}}', body: 'Olá {{client_name}},\n\nSeu cadastro foi realizado com sucesso!\n\nEnvie seus documentos pelo portal para iniciarmos os serviços.\n\nAtenciosamente,', from: 'contato@{{company_domain}}' } },
  { niche: Niche.ACCOUNTING, type: TemplateType.EMAIL, name: 'Fatura Mensalidade', description: 'Email com fatura de mensalidade contábil', isDefault: true, content: { subject: 'Mensalidade {{month}} - {{company_name}}', body: 'Olá {{client_name}},\n\nMensalidade de {{month}}: R$ {{amount}}\nVencimento: {{due_date}}\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.ACCOUNTING, type: TemplateType.EMAIL, name: 'Solicitar Documentos', description: 'Email solicitando documentos para obrigações', isDefault: true, content: { subject: 'Documentos necessários - {{month}}', body: 'Olá {{client_name}},\n\nPara cumprimento das obrigações de {{month}}, precisamos dos seguintes documentos:\n\n{{documents_list}}\n\nPrazo: {{deadline}}', from: 'contabil@{{company_domain}}' } },
  { niche: Niche.ACCOUNTING, type: TemplateType.EMAIL, name: 'Obrigação Entregue', description: 'Confirmação de entrega de obrigação', isDefault: false, content: { subject: '{{obligation_name}} entregue com sucesso', body: 'Olá {{client_name}},\n\nA obrigação {{obligation_name}} referente a {{period}} foi entregue.\n\nRecibo disponível no portal.', from: 'contabil@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.ACCOUNTING, type: TemplateType.REPORT, name: 'DRE Contábil', description: 'DRE para escritório contábil', isDefault: true, content: { sections: [{ title: 'Receita', items: ['mensalidades', 'declaracoes_extras', 'consultoria', 'auditoria'] }, { title: 'Custos', items: ['sistemas', 'certificados', 'correspondentes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.ACCOUNTING, type: TemplateType.REPORT, name: 'Relatório de Clientes', description: 'Análise da carteira de clientes', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_clientes', 'novos_mes', 'cancelamentos'] }, { title: 'Por Regime', items: ['simples_nacional', 'lucro_presumido', 'lucro_real', 'mei'] }, { title: 'Por Atividade', items: ['comercio', 'servicos', 'industria', 'profissional_liberal'] }], period: 'monthly' } },
  { niche: Niche.ACCOUNTING, type: TemplateType.REPORT, name: 'Relatório de Obrigações', description: 'Obrigações entregues e pendentes', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['entregues', 'pendentes', 'atrasadas'] }, { title: 'Por Tipo', items: ['sped_fiscal', 'sped_contribuicoes', 'dctf', 'ecf', 'dirpf', 'dms', 'gia'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.ACCOUNTING, type: TemplateType.INVOICE, name: 'NFS-e Contabilidade', description: 'NFS-e para serviços contábeis', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.02', natureza: 'Serviço de Contabilidade', campos_adicionais: ['crc_contador', 'cliente', 'periodo'] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.INVOICE, name: 'Fatura Mensalidade Contábil', description: 'Layout de fatura de mensalidade', isDefault: true, content: { formato: 'fatura', campos: ['cliente', 'competencia', 'servicos_inclusos', 'valor', 'vencimento', 'pix'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.ACCOUNTING, type: TemplateType.PRODUCT_CATALOG, name: 'Serviços Contábeis', description: 'Categorias de serviços do escritório', isDefault: true, content: { categories: ['Escrituração', 'Declarações', 'Folha de Pagamento', 'Fiscal', 'Consultoria', 'Auditoria', 'Abertura de Empresa', 'Certificado Digital'] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Contábil', description: 'Unidades de medida para contabilidade', isDefault: true, content: { units: [{ code: 'MENS', name: 'Mensalidade' }, { code: 'DECL', name: 'Declaração' }, { code: 'H', name: 'Hora' }, { code: 'UN', name: 'Unidade' }, { code: 'FUNC', name: 'Funcionário/Mês' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Contábil', description: 'Margens sugeridas por tipo de serviço', isDefault: false, content: { margins: [{ category: 'Escrituração', margin: 0.55 }, { category: 'Declarações', margin: 0.60 }, { category: 'Folha', margin: 0.50 }, { category: 'Consultoria', margin: 0.70 }] } },
  // 2 ONBOARDING
  { niche: Niche.ACCOUNTING, type: TemplateType.ONBOARDING, name: 'Setup Escritório', description: 'Configuração inicial para escritório contábil', isDefault: true, content: { steps: [{ id: 1, title: 'Dados do Escritório', fields: ['cnpj', 'razao_social', 'crc'] }, { id: 2, title: 'Cadastrar Contadores', action: 'create_accountants' }, { id: 3, title: 'Cadastrar Clientes', action: 'import_clients' }, { id: 4, title: 'Configurar Calendário Fiscal', action: 'setup_calendar' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.ONBOARDING, name: 'Migração de Carteira', description: 'Migrar carteira de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Clientes', action: 'import_clients' }, { id: 3, title: 'Importar Financeiro', action: 'import_finance' }, { id: 4, title: 'Configurar Obrigações', action: 'setup_obligations' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.ACCOUNTING, type: TemplateType.NICHE_SPECIFIC, name: 'Calendário Fiscal', description: 'Calendário de obrigações acessórias', isDefault: true, content: { obligations: [{ name: 'SPED Fiscal', deadline: 15, frequency: 'monthly' }, { name: 'DCTF', deadline: 5, frequency: 'monthly' }, { name: 'DIRF', deadline: 'february_last', frequency: 'yearly' }, { name: 'ECF', deadline: 'july_last', frequency: 'yearly' }, { name: 'SPED Contribuições', deadline: 10, frequency: 'monthly' }] } },
  { niche: Niche.ACCOUNTING, type: TemplateType.NICHE_SPECIFIC, name: 'Protocolo de Documentos', description: 'Sistema de protocolo para documentos de clientes', isDefault: true, content: { fields: ['cliente', 'tipo_documento', 'data_recebimento', 'responsavel', 'status', 'prazo_retorno'], auto_acknowledge: true } },
  { niche: Niche.ACCOUNTING, type: TemplateType.NICHE_SPECIFIC, name: 'Pricing por Funcionário', description: 'Tabela de preços baseada em número de funcionários', isDefault: false, content: { tiers: [{ range: '1-5', price: 250 }, { range: '6-15', price: 450 }, { range: '16-30', price: 750 }, { range: '31-50', price: 1200 }, { range: '50+', price: 'custom' }] } },
];

export { BEAUTY_TEMPLATES, FITNESS_TEMPLATES, LEGAL_TEMPLATES, ACCOUNTING_TEMPLATES };
