import { Niche, TemplateType } from '@prisma/client';

interface TemplateSeed {
  niche: Niche;
  type: TemplateType;
  name: string;
  description: string;
  content: Record<string, any>;
  isDefault: boolean;
}

// ─── RETAIL ────────────────────────────────────────────────────────────────
const RETAIL_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.RETAIL, type: TemplateType.WORKFLOW, name: 'Cobrança Automática', description: 'Workflow de cobrança para clientes inadimplentes no varejo', isDefault: true, content: { steps: [{ id: 1, name: 'Aguardar Vencimento', trigger: 'invoice_overdue_1d', action: 'wait' }, { id: 2, name: 'Enviar Lembrete Email', trigger: 'timer_1d', action: 'send_email', template: 'lembrete-cobranca' }, { id: 3, name: 'Enviar SMS', trigger: 'timer_3d', action: 'send_sms', template: 'sms-cobranca' }, { id: 4, name: 'Notificar Financeiro', trigger: 'timer_7d', action: 'notify', target: 'finance' }, { id: 5, name: 'Marcar como Inadimplente', trigger: 'timer_15d', action: 'update_customer', segment: 'AT_RISK' }] } },
  { niche: Niche.RETAIL, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Fluxo de boas-vindas e configuração para novos clientes', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Boas-vindas', trigger: 'customer_created', action: 'send_email', template: 'boas-vindas-varejo' }, { id: 2, name: 'Criar Conta no App', trigger: 'timer_1d', action: 'check_condition', field: 'app_registered' }, { id: 3, name: 'Lembrete Cadastro App', trigger: 'timer_3d', action: 'send_sms', template: 'sms-cadastro-app' }, { id: 4, name: 'Oferecer Primeira Compra', trigger: 'timer_7d', action: 'send_email', template: 'primeira-compra-desconto' }] } },
  { niche: Niche.RETAIL, type: TemplateType.WORKFLOW, name: 'Alerta de Estoque Baixo', description: 'Notifica quando produtos atingem nível mínimo de estoque', isDefault: true, content: { steps: [{ id: 1, name: 'Verificar Estoque', trigger: 'daily_check', action: 'check_stock', threshold: 10 }, { id: 2, name: 'Notificar Compras', trigger: 'stock_below_threshold', action: 'notify', target: 'purchasing' }, { id: 3, name: 'Gerar Pedido Automático', trigger: 'stock_critical', action: 'create_purchase_order', autoApprove: false }] } },
  { niche: Niche.RETAIL, type: TemplateType.WORKFLOW, name: 'Follow-up Pós-Venda', description: 'Acompanhamento após compra para satisfação e recompra', isDefault: false, content: { steps: [{ id: 1, name: 'Pesquisa Satisfação', trigger: 'sale_completed_3d', action: 'send_email', template: 'pesquisa-satisfacao' }, { id: 2, name: 'Oferta Recompra', trigger: 'timer_15d', action: 'send_email', template: 'oferta-recompra' }, { id: 3, name: 'Programa Fidelidade', trigger: 'timer_30d', action: 'update_customer', loyalty: true }] } },
  { niche: Niche.RETAIL, type: TemplateType.WORKFLOW, name: 'Troca e Devolução', description: 'Processo completo de troca e devolução de produtos', isDefault: false, content: { steps: [{ id: 1, name: 'Registrar Solicitação', trigger: 'return_requested', action: 'create_ticket' }, { id: 2, name: 'Analisar Motivo', trigger: 'ticket_created', action: 'notify', target: 'support' }, { id: 3, name: 'Aprovar/Recusar', trigger: 'analysis_complete', action: 'update_ticket' }, { id: 4, name: 'Processar Reembolso', trigger: 'return_approved', action: 'create_refund' }, { id: 5, name: 'Atualizar Estoque', trigger: 'refund_processed', action: 'update_stock', quantity: 1 }] } },
  // 3 DASHBOARD
  { niche: Niche.RETAIL, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira completa do varejo', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'expenses', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'margin', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'store', 'category'] } },
  { niche: Niche.RETAIL, type: TemplateType.DASHBOARD, name: 'Dashboard Operacional', description: 'Métricas de operação diária do varejo', isDefault: false, content: { widgets: [{ type: 'daily_sales', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'stock_alerts', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'top_products', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'pending_orders', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'store'] } },
  { niche: Niche.RETAIL, type: TemplateType.DASHBOARD, name: 'Dashboard de Vendas', description: 'Análise de vendas, ticket médio e conversão', isDefault: false, content: { widgets: [{ type: 'sales_trend', position: { x: 0, y: 0, w: 8, h: 4 } }, { type: 'avg_ticket', position: { x: 8, y: 0, w: 4, h: 2 } }, { type: 'conversion_rate', position: { x: 8, y: 2, w: 4, h: 2 } }, { type: 'sales_by_category', position: { x: 0, y: 4, w: 6, h: 4 } }, { type: 'sales_by_channel', position: { x: 6, y: 4, w: 6, h: 4 } }], filters: ['period', 'store', 'seller'] } },
  // 4 EMAIL
  { niche: Niche.RETAIL, type: TemplateType.EMAIL, name: 'Boas-vindas Varejo', description: 'Email de boas-vindas para novos clientes do varejo', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nQue bom ter você conosco! Na {{company_name}}, você encontra os melhores produtos com atendimento personalizado.\n\nAproveite 10% de desconto na sua primeira compra com o cupom BEMVINDO10.\n\nAté breve!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.RETAIL, type: TemplateType.EMAIL, name: 'Cobrança Amigável', description: 'Email de cobrança com tom amigável', isDefault: true, content: { subject: 'Lembrete: sua fatura vence em {{days_until_due}} dias', body: 'Olá {{customer_name}},\n\nSua fatura no valor de R$ {{amount}} vence em {{due_date}}.\n\nSe já realizou o pagamento, desconsidere este email.\n\nQualquer dúvida, entre em contato.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.RETAIL, type: TemplateType.EMAIL, name: 'Follow-up Pós-Compra', description: 'Acompanhamento após a compra', isDefault: false, content: { subject: 'Como foi sua experiência, {{customer_name}}?', body: 'Olá {{customer_name}},\n\nRecentemente você comprou {{product_name}} na nossa loja. Gostaríamos de saber como foi sua experiência.\n\nSua opinião é muito importante para nós!\n\nObrigado,', from: 'sac@{{company_domain}}' } },
  { niche: Niche.RETAIL, type: TemplateType.EMAIL, name: 'Relatório Mensal', description: 'Resumo mensal de atividades para o cliente', isDefault: false, content: { subject: 'Seu resumo mensal - {{month}}/{{year}}', body: 'Olá {{customer_name}},\n\nAqui está seu resumo do mês:\n- Compras: {{total_purchases}}\n- Pontos de fidelidade: {{loyalty_points}}\n- Descontos ganhos: R$ {{discounts_earned}}\n\nContinue aproveitando!', from: 'relacionamento@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.RETAIL, type: TemplateType.REPORT, name: 'DRE Simplificado', description: 'Demonstrativo de Resultados simplificado para varejo', isDefault: true, content: { sections: [{ title: 'Receita Bruta', items: ['vendas_loja', 'vendas_online', 'vendas_atacado'] }, { title: 'Deduções', items: ['devolucoes', 'descontos', 'impostos'] }, { title: 'Custo Mercadorias', items: ['cmv', 'frete_compra'] }, { title: 'Despesas Operacionais', items: ['aluguel', 'pessoal', 'marketing', 'outros'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido', 'margem'] }], period: 'monthly' } },
  { niche: Niche.RETAIL, type: TemplateType.REPORT, name: 'Fluxo de Caixa', description: 'Projeção de fluxo de caixa para varejo', isDefault: true, content: { sections: [{ title: 'Entradas', items: ['vendas_dinheiro', 'vendas_debito', 'recebiveis_cartao', 'outras_entradas'] }, { title: 'Saídas', items: ['fornecedores', 'folha_pagamento', 'aluguel', 'impostos', 'outras_saidas'] }, { title: 'Saldo', items: ['saldo_dia', 'saldo_acumulado', 'saldo_projetado_30d'] }], period: 'daily' } },
  { niche: Niche.RETAIL, type: TemplateType.REPORT, name: 'Relatório de Vendas', description: 'Análise detalhada de vendas por período, categoria e canal', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_vendas', 'ticket_medio', 'itens_vendidos', 'devolucoes'] }, { title: 'Por Categoria', items: ['categorias_top5', 'categorias_crescimento'] }, { title: 'Por Canal', items: ['loja_fisica', 'online', 'atacado'] }, { title: 'Por Vendedor', items: ['ranking_vendedores', 'meta_atingida'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.RETAIL, type: TemplateType.INVOICE, name: 'NF-e Varejo', description: 'Modelo de Nota Fiscal Eletrônica para varejo', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Mercadoria', campos_adicionais: ['peso_liquido', 'volume', 'marca'] } },
  { niche: Niche.RETAIL, type: TemplateType.INVOICE, name: 'NFC-e PDV', description: 'Modelo de NFC-e para ponto de venda', isDefault: true, content: { modelo: '65', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda ao Consumidor', campos_adicionais: ['qr_code', 'chave_acesso'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.RETAIL, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias Varejo Geral', description: 'Categorias de produtos padrão para varejo', isDefault: true, content: { categories: ['Alimentos', 'Bebidas', 'Higiene', 'Limpeza', 'Papelaria', 'Utilidades', 'Pet', 'Materno'] } },
  { niche: Niche.RETAIL, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades de Medida Varejo', description: 'Unidades padrão para produtos de varejo', isDefault: true, content: { units: [{ code: 'UN', name: 'Unidade' }, { code: 'KG', name: 'Quilograma' }, { code: 'L', name: 'Litro' }, { code: 'M', name: 'Metro' }, { code: 'PCT', name: 'Pacote' }, { code: 'CX', name: 'Caixa' }, { code: 'FD', name: 'Fardo' }] } },
  { niche: Niche.RETAIL, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Padrão Varejo', description: 'Margens de lucro sugeridas por categoria', isDefault: false, content: { margins: [{ category: 'Alimentos', margin: 0.25 }, { category: 'Bebidas', margin: 0.30 }, { category: 'Higiene', margin: 0.40 }, { category: 'Limpeza', margin: 0.35 }, { category: 'Papelaria', margin: 0.50 }, { category: 'Utilidades', margin: 0.45 }] } },
  // 2 ONBOARDING
  { niche: Niche.RETAIL, type: TemplateType.ONBOARDING, name: 'Setup Inicial Varejo', description: 'Configuração inicial completa para loja de varejo', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Empresa', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Configurar PDV', fields: ['caixa', 'ecf_serie', 'certificado_digital'] }, { id: 3, title: 'Cadastrar Produtos', action: 'import_csv' }, { id: 4, title: 'Configurar NFC-e', fields: ['serie', 'numero_inicial', 'ambiente'] }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.RETAIL, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Passos para migrar dados de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Dados Antigos', description: 'Exporte clientes, produtos e financeiro do sistema anterior' }, { id: 2, title: 'Formatar CSV', description: 'Adequar colunas ao template de importação BusinessOS' }, { id: 3, title: 'Importar Clientes', action: 'import', entity: 'customers' }, { id: 4, title: 'Importar Produtos', action: 'import', entity: 'products' }, { id: 5, title: 'Importar Financeiro', action: 'import', entity: 'transactions' }, { id: 6, title: 'Validar Dados', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.RETAIL, type: TemplateType.NICHE_SPECIFIC, name: 'Programa de Fidelidade', description: 'Configuração de programa de pontos para varejo', isDefault: false, content: { rules: { points_per_real: 1, minimum_purchase: 20, expiration_days: 180, tiers: [{ name: 'Bronze', min_points: 0, discount: 0 }, { name: 'Prata', min_points: 500, discount: 5 }, { name: 'Ouro', min_points: 1500, discount: 10 }, { name: 'Diamante', min_points: 5000, discount: 15 }] } } },
  { niche: Niche.RETAIL, type: TemplateType.NICHE_SPECIFIC, name: 'Gestão de Promoções', description: 'Template para criar e gerenciar campanhas promocionais', isDefault: false, content: { campaign_types: ['desconto_percentual', 'leve_mais_pague_menos', 'compre_ganhe', 'cashback'], default_duration_days: 7, auto_deactivate: true } },
  { niche: Niche.RETAIL, type: TemplateType.NICHE_SPECIFIC, name: 'Controle de Caixa', description: 'Abertura, sangria e fechamento de caixa diário', isDefault: true, content: { operations: ['abertura', 'sangria', 'reforco', 'fechamento'], denominations: [200, 100, 50, 20, 10, 5, 2, 1, 0.50, 0.25, 0.10, 0.05], required_fields: ['valor_abertura', 'operador', 'forma_pagamento'] } },
];

// ─── ECOMMERCE ─────────────────────────────────────────────────────────────
const ECOMMERCE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.ECOMMERCE, type: TemplateType.WORKFLOW, name: 'Cobrança E-commerce', description: 'Workflow de cobrança para pedidos online', isDefault: true, content: { steps: [{ id: 1, name: 'Pedido Pendente', trigger: 'order_pending_payment', action: 'wait', timeout: '2h' }, { id: 2, name: 'Email de Pagamento', trigger: 'timer_2h', action: 'send_email', template: 'pagamento-pendente' }, { id: 3, name: 'Cancelar Pedido', trigger: 'timer_48h', action: 'cancel_order' }, { id: 4, name: 'Notificar Cliente', trigger: 'order_cancelled', action: 'send_email', template: 'pedido-cancelado' }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.WORKFLOW, name: 'Onboarding E-commerce', description: 'Boas-vindas e engajamento para novo cliente online', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'customer_registered', action: 'send_email', template: 'boas-vindas-ecommerce' }, { id: 2, name: 'Cupom Primeira Compra', trigger: 'timer_1d', action: 'send_email', template: 'cupom-primeira-compra' }, { id: 3, name: 'Lembrete Carrinho', trigger: 'cart_abandoned_24h', action: 'send_email', template: 'carrinho-abandonado' }, { id: 4, name: 'NPS 30 dias', trigger: 'first_purchase_30d', action: 'send_email', template: 'pesquisa-nps' }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.WORKFLOW, name: 'Carrinho Abandonado', description: 'Recuperação de vendas com carrinhos abandonados', isDefault: true, content: { steps: [{ id: 1, name: 'Lembreto 4h', trigger: 'cart_abandoned_4h', action: 'send_email', template: 'carrinho-lembrete' }, { id: 2, name: 'Oferta Desconto 24h', trigger: 'cart_abandoned_24h', action: 'send_email', template: 'carrinho-desconto', discount: 10 }, { id: 3, name: 'Última Chance 72h', trigger: 'cart_abandoned_72h', action: 'send_email', template: 'carrinho-ultima-chance' }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.WORKFLOW, name: 'Rastreamento de Pedido', description: 'Atualizações automáticas de status de entrega', isDefault: false, content: { steps: [{ id: 1, name: 'Confirmação Pagamento', trigger: 'payment_confirmed', action: 'send_email', template: 'pagamento-confirmado' }, { id: 2, name: 'Pedido Em Separacao', trigger: 'order_picking', action: 'send_email', template: 'pedido-separacao' }, { id: 3, name: 'Pedido Enviado', trigger: 'order_shipped', action: 'send_email', template: 'pedido-enviado' }, { id: 4, name: 'Entregue', trigger: 'order_delivered', action: 'send_email', template: 'pedido-entregue' }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.WORKFLOW, name: 'Devolução Online', description: 'Processo de troca e devolução para e-commerce', isDefault: false, content: { steps: [{ id: 1, name: 'Solicitação Recebida', trigger: 'return_requested', action: 'create_ticket' }, { id: 2, name: 'Código Postagem', trigger: 'return_approved', action: 'send_email', template: 'codigo-postagem' }, { id: 3, name: 'Produto Recebido', trigger: 'package_received', action: 'notify', target: 'warehouse' }, { id: 4, name: 'Reembolso', trigger: 'product_inspected', action: 'process_refund' }] } },
  // 3 DASHBOARD
  { niche: Niche.ECOMMERCE, type: TemplateType.DASHBOARD, name: 'Dashboard E-commerce', description: 'Visão geral do e-commerce com vendas e conversão', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'conversion_funnel', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'avg_ticket', position: { x: 0, y: 4, w: 4, h: 4 } }, { type: 'cart_abandonment', position: { x: 4, y: 4, w: 4, h: 4 } }, { type: 'top_products', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'channel'] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.DASHBOARD, name: 'Dashboard de Marketing', description: 'Métricas de campanhas e aquisição', isDefault: false, content: { widgets: [{ type: 'campaigns_roi', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'traffic_sources', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'email_metrics', position: { x: 0, y: 4, w: 4, h: 4 } }, { type: 'social_metrics', position: { x: 4, y: 4, w: 4, h: 4 } }], filters: ['period', 'channel', 'campaign'] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.DASHBOARD, name: 'Dashboard Logística', description: 'Acompanhamento de entregas e estoque', isDefault: false, content: { widgets: [{ type: 'shipping_status', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'delivery_time', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'stock_coverage', position: { x: 0, y: 4, w: 6, h: 4 } }, { type: 'return_rate', position: { x: 6, y: 4, w: 6, h: 4 } }], filters: ['period', 'carrier'] } },
  // 4 EMAIL
  { niche: Niche.ECOMMERCE, type: TemplateType.EMAIL, name: 'Boas-vindas E-commerce', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nSua conta foi criada com sucesso! Explore nossa loja e aproveite 15% OFF na primeira compra com o cupom WELCOME15.\n\nFrete grátis em compras acima de R$ 199.', from: 'contato@{{company_domain}}' } },
  { niche: Niche.ECOMMERCE, type: TemplateType.EMAIL, name: 'Carrinho Abandonado', description: 'Email de recuperação de carrinho abandonado', isDefault: true, content: { subject: '{{customer_name}}, seus produtos estão te esperando!', body: 'Olá {{customer_name}},\n\nVocê esqueceu alguns itens no carrinho:\n\n{{cart_items}}\n\nComplete sua compra agora e ganhe 10% de desconto com o cupom VOLTA10.', from: 'marketing@{{company_domain}}' } },
  { niche: Niche.ECOMMERCE, type: TemplateType.EMAIL, name: 'Pedido Enviado', description: 'Notificação de envio com rastreio', isDefault: true, content: { subject: 'Seu pedido #{{order_id}} foi enviado!', body: 'Olá {{customer_name}},\n\nSeu pedido foi enviado!\n\nRastreio: {{tracking_code}}\nTransportadora: {{carrier_name}}\nPrevisão: {{estimated_delivery}}\n\nAcompanhe seu pedido.', from: 'pedidos@{{company_domain}}' } },
  { niche: Niche.ECOMMERCE, type: TemplateType.EMAIL, name: 'Relatório Semanal', description: 'Resumo semanal de pedidos e novidades', isDefault: false, content: { subject: 'Novidades da semana - {{company_name}}', body: 'Olá {{customer_name}},\n\nConfira as novidades da semana:\n- Novos produtos\n- Promoções especiais\n- Seus pontos: {{loyalty_points}}\n\nAcesse nossa loja!', from: 'news@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.ECOMMERCE, type: TemplateType.REPORT, name: 'DRE E-commerce', description: 'DRE focado em operações digitais', isDefault: true, content: { sections: [{ title: 'Receita', items: ['vendas_site', 'vendas_marketplace', 'assinaturas'] }, { title: 'Deduções', items: ['devolucoes', 'cupons', 'marketplace_fee', 'impostos'] }, { title: 'Custos', items: ['cmv', 'frete_saida', 'embalagem'] }, { title: 'Despesas', items: ['hospedagem', 'marketing_digital', 'pessoal', 'erp'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.ECOMMERCE, type: TemplateType.REPORT, name: 'Relatório de Conversão', description: 'Funil de conversão e métricas de aquisição', isDefault: false, content: { sections: [{ title: 'Funil', items: ['visitantes', 'visualizaram_produto', 'adicionaram_carrinho', 'iniciaram_checkout', 'compraram'] }, { title: 'Taxas', items: ['taxa_conversao', 'taxa_abandono_carrinho', 'taxa_rejeicao'] }, { title: 'Canais', items: ['organico', 'pago', 'direto', 'social', 'email'] }], period: 'weekly' } },
  { niche: Niche.ECOMMERCE, type: TemplateType.REPORT, name: 'Relatório de Logística', description: 'Desempenho de entregas e devoluções', isDefault: false, content: { sections: [{ title: 'Entregas', items: ['pedidos_enviados', 'tempo_medio_entrega', 'custo_frete_medio'] }, { title: 'Devoluções', items: ['total_devolucoes', 'taxa_devolucao', 'motivos_devolucao'] }, { title: 'Transportadoras', items: ['ranking_transportadoras', 'atrasos', 'extravios'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.ECOMMERCE, type: TemplateType.INVOICE, name: 'NF-e E-commerce', description: 'NF-e para venda online interestadual', isDefault: true, content: { modelo: '55', serie: '2', cfop: '6102', cst_icms: '00', csosn: '102', natureza: 'Venda Online', campos_adicionais: ['frete', 'modalidade_frete', 'rastreio'] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.INVOICE, name: 'Invoice Internacional', description: 'Layout de invoice para exportação', isDefault: false, content: { formato: 'internacional', idioma: 'en', campos: ['invoice_number', 'date', 'buyer', 'items', 'total', 'shipping', 'currency'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.ECOMMERCE, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias E-commerce', description: 'Categorias de produtos para loja online', isDefault: true, content: { categories: ['Eletrônicos', 'Moda', 'Casa e Decoração', 'Beleza', 'Esportes', 'Livros', 'Alimentos', 'Brinquedos'] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.PRODUCT_CATALOG, name: 'Atributos de Produto', description: 'Atributos padrão para ficha de produto online', isDefault: true, content: { attributes: ['peso', 'dimensoes', 'cor', 'tamanho', 'material', 'garantia', 'marca', 'sku_fabricante', 'ean'] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Marketplace', description: 'Margens considerando taxas de marketplaces', isDefault: false, content: { margins: [{ channel: 'proprio', margin: 0.40 }, { channel: 'mercadolivre', margin: 0.25, fee: 0.16 }, { channel: 'magalu', margin: 0.22, fee: 0.18 }, { channel: 'amazon', margin: 0.20, fee: 0.20 }, { channel: 'shopee', margin: 0.28, fee: 0.12 }] } },
  // 2 ONBOARDING
  { niche: Niche.ECOMMERCE, type: TemplateType.ONBOARDING, name: 'Setup E-commerce', description: 'Configuração inicial para loja online', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Loja', fields: ['cnpj', 'razao_social', 'url_loja'] }, { id: 2, title: 'Integrações', fields: ['gateway_pagamento', 'correios', 'erp'] }, { id: 3, title: 'Cadastrar Produtos', action: 'import_csv' }, { id: 4, title: 'Configurar Frete', fields: ['cep_origem', 'transportadoras'] }, { id: 5, title: 'Ir ao Ar!', action: 'publish' }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.ONBOARDING, name: 'Migração de Plataforma', description: 'Migrar de outra plataforma de e-commerce', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Dados Antigos', description: 'Exporte de Shopify/Nuvemshop/WooCommerce' }, { id: 2, title: 'Mapear Categorias', action: 'map_categories' }, { id: 3, title: 'Importar Produtos', action: 'import_products' }, { id: 4, title: 'Importar Clientes', action: 'import_customers' }, { id: 5, title: 'Importar Pedidos', action: 'import_orders' }, { id: 6, title: 'Configurar Redirects 301', action: 'setup_redirects' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.ECOMMERCE, type: TemplateType.NICHE_SPECIFIC, name: 'Regras de Frete', description: 'Configuração de regras de frete e envio', isDefault: true, content: { rules: [{ type: 'free_shipping', min_value: 199 }, { type: 'flat_rate', regions: ['sudeste'], value: 15.90 }, { type: 'flat_rate', regions: ['sul_nordeste'], value: 22.90 }, { type: 'flat_rate', regions: ['norte_centroeste'], value: 35.90 }, { type: 'express', additional: 12.00 }] } },
  { niche: Niche.ECOMMERCE, type: TemplateType.NICHE_SPECIFIC, name: 'Gateway de Pagamento', description: 'Configuração de gateways e split', isDefault: true, content: { gateways: ['pagseguro', 'mercadopago', 'stripe'], installments: { max: 12, interest_from: 7, interest_rate: 0.0199 }, pix_discount: 5 } },
  { niche: Niche.ECOMMERCE, type: TemplateType.NICHE_SPECIFIC, name: 'SEO de Produto', description: 'Checklist de otimização SEO para ficha de produto', isDefault: false, content: { checklist: ['titulo_ate_60_chars', 'descricao_min_300_chars', 'alt_text_imagens', 'url_amigavel', 'schema_markup', 'meta_description', 'tags_h1_h2'] } },
];

// ─── FOOD_SERVICE ──────────────────────────────────────────────────────────
const FOOD_SERVICE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.FOOD_SERVICE, type: TemplateType.WORKFLOW, name: 'Cobrança de Inadimplentes', description: 'Workflow de cobrança para estabelecimentos alimentícios', isDefault: true, content: { steps: [{ id: 1, name: 'Vencimento', trigger: 'invoice_overdue_1d', action: 'send_email', template: 'cobranca-almoco' }, { id: 2, name: 'Segundo Aviso', trigger: 'timer_3d', action: 'send_sms', template: 'segundo-aviso' }, { id: 3, name: 'Bloquear Crédito', trigger: 'timer_7d', action: 'block_credit' }, { id: 4, name: 'Notificar Gerência', trigger: 'timer_15d', action: 'notify', target: 'manager' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.WORKFLOW, name: 'Onboarding Cliente', description: 'Boas-vindas para novos clientes de restaurante/delivery', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'customer_created', action: 'send_email', template: 'boas-vindas-food' }, { id: 2, name: 'Cupom Primeiro Pedido', trigger: 'timer_1d', action: 'send_email', template: 'cupom-primeiro-pedido' }, { id: 3, name: 'Pesquisa Satisfação', trigger: 'first_order_7d', action: 'send_email', template: 'nps-food' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.WORKFLOW, name: 'Controle de Validade', description: 'Alerta automático para produtos próximos ao vencimento', isDefault: true, content: { steps: [{ id: 1, name: 'Verificar Validades', trigger: 'daily_check', action: 'check_expiry', days_before: 3 }, { id: 2, name: 'Alerta Cozinha', trigger: 'expiry_near', action: 'notify', target: 'kitchen' }, { id: 3, name: 'Marcar Descarte', trigger: 'expiry_reached', action: 'mark_for_disposal' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.WORKFLOW, name: 'Pedido de Compra', description: 'Geração automática de pedidos para fornecedores', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Estoque Mínimo', trigger: 'daily_check', action: 'check_stock' }, { id: 2, name: 'Gerar Lista', trigger: 'stock_low', action: 'generate_purchase_list' }, { id: 3, name: 'Enviar para Fornecedores', trigger: 'list_generated', action: 'send_email', template: 'pedido-fornecedor' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.WORKFLOW, name: 'Reserva de Mesa', description: 'Fluxo de confirmação e lembrete de reservas', isDefault: false, content: { steps: [{ id: 1, name: 'Confirmar Reserva', trigger: 'reservation_created', action: 'send_email', template: 'confirmacao-reserva' }, { id: 2, name: 'Lembrete 2h Antes', trigger: 'reservation_2h_before', action: 'send_sms', template: 'lembrete-reserva' }, { id: 3, name: 'No-show', trigger: 'reservation_missed', action: 'mark_no_show' }] } },
  // 3 DASHBOARD
  { niche: Niche.FOOD_SERVICE, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira do restaurante', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'food_cost', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'avg_ticket', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'store'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.DASHBOARD, name: 'Dashboard Operacional', description: 'Métricas operacionais do restaurante', isDefault: false, content: { widgets: [{ type: 'orders_today', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'avg_prep_time', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'waste_percentage', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'stock_alerts', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'store'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.DASHBOARD, name: 'Dashboard Delivery', description: 'Métricas de delivery e iFood', isDefault: false, content: { widgets: [{ type: 'delivery_orders', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'avg_delivery_time', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'delivery_revenue', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'ifood_rating', position: { x: 0, y: 4, w: 4, h: 4 } }, { type: 'platform_comparison', position: { x: 4, y: 4, w: 8, h: 4 } }], filters: ['period', 'platform'] } },
  // 4 EMAIL
  { niche: Niche.FOOD_SERVICE, type: TemplateType.EMAIL, name: 'Boas-vindas Restaurante', description: 'Email de boas-vindas para clientes do restaurante', isDefault: true, content: { subject: 'Bem-vindo(a) ao {{company_name}}!', body: 'Olá {{customer_name}},\n\nQue bom ter você com a gente! Aproveite 20% OFF no seu primeiro pedido com o cupom SABOR20.\n\nBom apetite!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.EMAIL, name: 'Cobrança Mensalista', description: 'Email de cobrança para clientes de plano mensal', isDefault: true, content: { subject: 'Sua mensalidade vence em {{due_date}}', body: 'Olá {{customer_name}},\n\nSua mensalidade de R$ {{amount}} vence em {{due_date}}.\n\nPara continuar aproveitando nossos serviços, mantenha seu pagamento em dia.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.EMAIL, name: 'NPS Pós-Refeição', description: 'Pesquisa de satisfação após a refeição', isDefault: false, content: { subject: 'Como foi sua experiência, {{customer_name}}?', body: 'Olá {{customer_name}},\n\nGostaríamos de saber como foi sua experiência no {{company_name}}.\n\nSua nota de 0 a 10 nos ajuda a melhorar cada dia mais!\n\nObrigado!', from: 'sac@{{company_domain}}' } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.EMAIL, name: 'Cardápio Atualizado', description: 'Notificação de novidades no cardápio', isDefault: false, content: { subject: 'Novidades no cardápio do {{company_name}}!', body: 'Olá {{customer_name}},\n\nTemos novidades deliciosas no cardápio! Confira:\n\n{{new_items}}\n\nVenha provar!', from: 'marketing@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.FOOD_SERVICE, type: TemplateType.REPORT, name: 'DRE Restaurante', description: 'DRE focado em restaurante com food cost', isDefault: true, content: { sections: [{ title: 'Receita', items: ['vendas_salao', 'vendas_delivery', 'vendas_eventos', 'delivery_apps'] }, { title: 'Custos', items: ['food_cost', 'beverage_cost', 'embalagens_delivery'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'gas_energia', 'marketing', 'taxas_delivery'] }, { title: 'Resultado', items: ['lucro_bruto', 'food_cost_pct', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.REPORT, name: 'Relatório de Food Cost', description: 'Análise de custo de ingredientes e desperdício', isDefault: true, content: { sections: [{ title: 'Custo de Ingredientes', items: ['total_compras', 'custo_por_prato', 'variacao_preco'] }, { title: 'Desperdício', items: ['desperdicio_kg', 'desperdicio_pct', 'itens_descartados'] }, { title: 'Margem por Prato', items: ['pratos_mais_lucrativos', 'pratos_margem_baixa', 'ajustes_sugeridos'] }], period: 'weekly' } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.REPORT, name: 'Relatório de Vendas', description: 'Análise de vendas por horário, dia e canal', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_vendas', 'ticket_medio', 'covers_dia'] }, { title: 'Por Horário', items: ['almoco', 'jantar', 'happy_hour', 'delivery_noturno'] }, { title: 'Por Canal', items: ['salao', 'delivery_direto', 'ifood', 'rappi', 'uber_eats'] }, { title: 'Top Itens', items: ['mais_vendidos', 'menos_vendidos'] }], period: 'daily' } },
  // 2 INVOICE
  { niche: Niche.FOOD_SERVICE, type: TemplateType.INVOICE, name: 'NF-e Restaurante', description: 'NF-e para restaurante', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Alimentação', campos_adicionais: ['couvert', 'gorjeta', 'taxa_servico'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.INVOICE, name: 'NFS-e Catering', description: 'NFS-e para serviço de catering/buffet', isDefault: false, content: { modelo: 'nfs-e', item_lista: '10.05', natureza: 'Serviço de Alimentação', campos_adicionais: ['evento', 'num_pessoas', 'data_evento', 'local'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.FOOD_SERVICE, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias Cardápio', description: 'Categorias padrão para cardápio', isDefault: true, content: { categories: ['Entradas', 'Pratos Principais', 'Sobremesas', 'Bebidas', 'Acompanhamentos', 'Kids', 'Combos', 'Promoções'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Alimentação', description: 'Unidades de medida para cozinha', isDefault: true, content: { units: [{ code: 'UN', name: 'Unidade' }, { code: 'KG', name: 'Quilograma' }, { code: 'L', name: 'Litro' }, { code: 'ML', name: 'Mililitro' }, { code: 'G', name: 'Grama' }, { code: 'POR', name: 'Porção' }, { code: 'PRATO', name: 'Prato' }, { code: 'COP', name: 'Copo' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Cardápio', description: 'Margens sugeridas por categoria do cardápio', isDefault: false, content: { margins: [{ category: 'Entradas', margin: 0.65 }, { category: 'Pratos Principais', margin: 0.55 }, { category: 'Sobremesas', margin: 0.70 }, { category: 'Bebidas', margin: 0.75 }, { category: 'Combos', margin: 0.45 }, { category: 'Kids', margin: 0.40 }] } },
  // 2 ONBOARDING
  { niche: Niche.FOOD_SERVICE, type: TemplateType.ONBOARDING, name: 'Setup Restaurante', description: 'Configuração inicial completa para restaurante', isDefault: true, content: { steps: [{ id: 1, title: 'Dados do Restaurante', fields: ['cnpj', 'razao_social', 'endereco', 'alvara'] }, { id: 2, title: 'Configurar Cardápio', action: 'import_menu' }, { id: 3, title: 'Configurar PDV', fields: ['caixa', 'impressora', 'balanca'] }, { id: 4, title: 'Integrar Delivery', fields: ['ifood', 'rappi'] }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.ONBOARDING, name: 'Migração de Sistema', description: 'Migrar dados de outro sistema de restaurante', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Dados', description: 'Exporte cardápio, clientes e financeiro' }, { id: 2, title: 'Importar Cardápio', action: 'import_menu' }, { id: 3, title: 'Importar Clientes', action: 'import_customers' }, { id: 4, title: 'Configurar PDV', action: 'setup_pos' }, { id: 5, title: 'Testar Operação', action: 'test_run' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.FOOD_SERVICE, type: TemplateType.NICHE_SPECIFIC, name: 'Ficha Técnica de Prato', description: 'Template para ficha técnica com custo e rendimento', isDefault: true, content: { fields: ['nome_prato', 'categoria', 'rendimento_porcoes', 'tempo_preparo_min', 'ingredientes', 'modo_preparo', 'custo_total', 'custo_por_porcao', 'margem_sugerida', 'alergenos'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.NICHE_SPECIFIC, name: 'Controle de Estoque Periódico', description: 'Inventário periódico com contagem e diferenças', isDefault: true, content: { frequency: 'weekly', locations: ['cozinha', 'estoque_frio', 'estoque_seco', 'bar'], fields: ['produto', 'unidade', 'estoque_sistema', 'contagem', 'diferenca', 'custo_diferenca'] } },
  { niche: Niche.FOOD_SERVICE, type: TemplateType.NICHE_SPECIFIC, name: 'Gestão de Delivery Apps', description: 'Configuração e controle de integrações com apps de delivery', isDefault: false, content: { platforms: ['ifood', 'rappi', 'uber_eats', '99food'], sync_fields: ['menu', 'pricing', 'availability', 'orders'], auto_accept: true, auto_update_stock: true } },
];

// ─── PROFESSIONAL_SERVICES ────────────────────────────────────────────────
const PROFESSIONAL_SERVICES_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.WORKFLOW, name: 'Cobrança de Honorários', description: 'Workflow de cobrança para serviços profissionais', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Fatura', trigger: 'invoice_created', action: 'send_email', template: 'fatura-honorarios' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-vencimento' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_1d', action: 'send_email', template: 'aviso-atraso' }, { id: 4, name: 'Suspender Serviço', trigger: 'invoice_overdue_15d', action: 'suspend_service' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Fluxo de integração de novo cliente de serviços', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Contrato', trigger: 'client_created', action: 'send_email', template: 'contrato-servicos' }, { id: 2, name: 'Reuniao Kickoff', trigger: 'contract_signed', action: 'schedule_meeting' }, { id: 3, name: 'Briefing', trigger: 'meeting_done', action: 'create_task', type: 'briefing' }, { id: 4, name: 'Iniciar Projeto', trigger: 'briefing_complete', action: 'update_project', status: 'active' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.WORKFLOW, name: 'Agendamento Automático', description: 'Lembretes e confirmação de agendamentos', isDefault: true, content: { steps: [{ id: 1, name: 'Confirmar Agendamento', trigger: 'appointment_created', action: 'send_email', template: 'confirmacao-agendamento' }, { id: 2, name: 'Lembrete 24h', trigger: 'appointment_24h_before', action: 'send_sms', template: 'lembrete-24h' }, { id: 3, name: 'Lembrete 2h', trigger: 'appointment_2h_before', action: 'send_sms', template: 'lembrete-2h' }, { id: 4, name: 'No-show', trigger: 'appointment_missed', action: 'mark_no_show' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.WORKFLOW, name: 'Follow-up Pós-Serviço', description: 'Acompanhamento após prestação de serviço', isDefault: false, content: { steps: [{ id: 1, name: 'Pesquisa Satisfação', trigger: 'service_completed_3d', action: 'send_email', template: 'nps-servico' }, { id: 2, name: 'Pedido de Avaliação', trigger: 'timer_7d', action: 'send_email', template: 'pedido-avaliacao' }, { id: 3, name: 'Oferta Novo Serviço', trigger: 'timer_30d', action: 'send_email', template: 'oferta-novo-servico' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.WORKFLOW, name: 'Gestão de Contratos', description: 'Renovação e alertas de contratos de serviço', isDefault: false, content: { steps: [{ id: 1, name: 'Alerta 30d Renovação', trigger: 'contract_expires_30d', action: 'notify', target: 'commercial' }, { id: 2, name: 'Proposta Renovação', trigger: 'timer_5d', action: 'send_email', template: 'proposta-renovacao' }, { id: 3, name: 'Segunda Tentativa', trigger: 'timer_15d', action: 'send_email', template: 'renovacao-segunda-tentativa' }, { id: 4, name: 'Desligamento', trigger: 'contract_expired', action: 'mark_inactive' }] } },
  // 3 DASHBOARD
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira de serviços profissionais', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'avg_hourly_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'service_type'] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard de Projetos', description: 'Acompanhamento de projetos e tarefas', isDefault: false, content: { widgets: [{ type: 'active_projects', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'project_timeline', position: { x: 4, y: 0, w: 8, h: 4 } }, { type: 'utilization_rate', position: { x: 0, y: 4, w: 4, h: 4 } }, { type: 'revenue_per_project', position: { x: 4, y: 4, w: 8, h: 4 } }], filters: ['period', 'client', 'status'] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.DASHBOARD, name: 'Dashboard de Agendamentos', description: 'Visão de agenda e ocupação', isDefault: false, content: { widgets: [{ type: 'today_schedule', position: { x: 0, y: 0, w: 6, h: 6 } }, { type: 'occupancy_rate', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'no_show_rate', position: { x: 6, y: 4, w: 6, h: 2 } }], filters: ['professional', 'period'] } },
  // 4 EMAIL
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.EMAIL, name: 'Boas-vindas Serviços', description: 'Email de boas-vindas para novo cliente de serviços', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nSeja bem-vindo(a)! Estamos à disposição para ajudá-lo.\n\nSeu projeto já está em andamento e você pode acompanhar pelo painel.\n\nAtenciosamente,', from: 'contato@{{company_domain}}' } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.EMAIL, name: 'Fatura de Honorários', description: 'Email com fatura de honorários', isDefault: true, content: { subject: 'Fatura #{{invoice_number}} - {{company_name}}', body: 'Olá {{customer_name}},\n\nSegue sua fatura no valor de R$ {{amount}} com vencimento em {{due_date}}.\n\nDados para pagamento:\nChave PIX: {{pix_key}}\n\nObrigado!', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.EMAIL, name: 'Confirmação de Agendamento', description: 'Confirmação de consulta/reunião', isDefault: true, content: { subject: 'Agendamento confirmado - {{date}} às {{time}}', body: 'Olá {{customer_name}},\n\nSeu agendamento está confirmado:\n\nData: {{date}}\nHorário: {{time}}\nProfissional: {{professional_name}}\n\nEm caso de cancelamento, avise com 24h de antecedência.', from: 'agenda@{{company_domain}}' } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.EMAIL, name: 'Relatório de Atividades', description: 'Relatório mensal de atividades e horas', isDefault: false, content: { subject: 'Relatório de atividades - {{month}}/{{year}}', body: 'Olá {{customer_name}},\n\nResumo do mês:\n- Horas trabalhadas: {{hours_worked}}\n- Tarefas concluídas: {{tasks_completed}}\n- Próximos passos: {{next_steps}}\n\nDúvidas? Entre em contato.', from: 'projetos@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.REPORT, name: 'DRE Serviços', description: 'DRE para prestação de serviços', isDefault: true, content: { sections: [{ title: 'Receita', items: ['honorarios', 'projetos', 'consultorias', 'recorrentes'] }, { title: 'Custos', items: ['subsistema', 'ferramentas', 'comissoes'] }, { title: 'Despesas', items: ['pessoal', 'escritorio', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'margem_bruta', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.REPORT, name: 'Relatório de Horas', description: 'Tracking de horas por projeto e profissional', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_horas', 'horas_faturaveis', 'taxa_aproveitamento'] }, { title: 'Por Projeto', items: ['projeto_horas', 'projeto_orcado_vs_real'] }, { title: 'Por Profissional', items: ['profissional_horas', 'profissional_produtividade'] }], period: 'weekly' } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.REPORT, name: 'Relatório de Clientes', description: 'Análise de carteira de clientes', isDefault: false, content: { sections: [{ title: 'Carteira', items: ['total_clientes_ativos', 'novos_clientes', 'churn_rate'] }, { title: 'Receita por Cliente', items: ['top10_receita', 'ltv_medio', 'receita_recorrente_pct'] }, { title: 'Inadimplência', items: ['total_inadimplente', 'aging_30_60_90', 'provisao'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.INVOICE, name: 'NFS-e Serviços', description: 'NFS-e para prestação de serviços', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.07', natureza: 'Prestação de Serviços', campos_adicionais: ['retencao_ir', 'retencao_iss', 'retencao_csll', 'retencao_pis_cofins'] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.INVOICE, name: 'Fatura de Honorários', description: 'Layout de fatura para cobrança de honorários', isDefault: true, content: { formato: 'fatura', campos: ['cliente', 'projeto', 'periodo', 'horas', 'valor_hora', 'total', 'impostos', 'liquido', 'pix'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias de Serviço', description: 'Categorias padrão para serviços profissionais', isDefault: true, content: { categories: ['Consultoria', 'Assessoria', 'Auditoria', 'Treinamento', 'Coaching', 'Design', 'Desenvolvimento', 'Suporte'] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades de Serviço', description: 'Unidades de medida para serviços', isDefault: true, content: { units: [{ code: 'H', name: 'Hora' }, { code: 'PROJ', name: 'Projeto' }, { code: 'MENS', name: 'Mensalidade' }, { code: 'SESS', name: 'Sessão' }, { code: 'UN', name: 'Unidade' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.PRODUCT_CATALOG, name: 'Margens por Tipo de Serviço', description: 'Margens sugeridas por tipo de serviço', isDefault: false, content: { margins: [{ category: 'Consultoria', margin: 0.60 }, { category: 'Assessoria', margin: 0.55 }, { category: 'Treinamento', margin: 0.50 }, { category: 'Suporte', margin: 0.45 }, { category: 'Design', margin: 0.65 }, { category: 'Desenvolvimento', margin: 0.55 }] } },
  // 2 ONBOARDING
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.ONBOARDING, name: 'Setup Escritório', description: 'Configuração inicial para escritório de serviços', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Empresa', fields: ['cnpj', 'razao_social', 'crc_crea_oab'] }, { id: 2, title: 'Configurar Serviços', action: 'create_services' }, { id: 3, title: 'Cadastrar Clientes', action: 'import_clients' }, { id: 4, title: 'Configurar NFS-e', fields: ['codigo_municipio', 'item_lista'] }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.ONBOARDING, name: 'Migração de Clientes', description: 'Migrar carteira de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Clientes', action: 'export' }, { id: 2, title: 'Importar Clientes', action: 'import' }, { id: 3, title: 'Importar Contratos', action: 'import_contracts' }, { id: 4, title: 'Importar Financeiro', action: 'import_transactions' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'Timesheet', description: 'Template de registro de horas trabalhadas', isDefault: true, content: { fields: ['data', 'projeto', 'cliente', 'tarefa', 'horas', 'descricao', 'faturavel'], approval_flow: true } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'Proposta Comercial', description: 'Estrutura de proposta comercial para serviços', isDefault: true, content: { sections: ['resumo_executivo', 'escopo', 'cronograma', 'equipe', 'investimento', 'condicoes', 'validade'], default_validity_days: 30 } },
  { niche: Niche.PROFESSIONAL_SERVICES, type: TemplateType.NICHE_SPECIFIC, name: 'SLA de Atendimento', description: 'Configuração de SLAs para serviços', isDefault: false, content: { tiers: [{ name: 'Básico', response_time: '24h', resolution_time: '72h', channels: ['email'] }, { name: 'Premium', response_time: '4h', resolution_time: '24h', channels: ['email', 'phone', 'whatsapp'] }, { name: 'VIP', response_time: '1h', resolution_time: '8h', channels: ['email', 'phone', 'whatsapp', 'dedicated_manager'] }] } },
];

// Export all template arrays for use in seed
export const ALL_NICHE_TEMPLATES: Record<string, TemplateSeed[]> = {
  RETAIL: RETAIL_TEMPLATES,
  ECOMMERCE: ECOMMERCE_TEMPLATES,
  FOOD_SERVICE: FOOD_SERVICE_TEMPLATES,
  PROFESSIONAL_SERVICES: PROFESSIONAL_SERVICES_TEMPLATES,
};
