import { Niche, TemplateType } from '@prisma/client';

interface TemplateSeed {
  niche: Niche;
  type: TemplateType;
  name: string;
  description: string;
  content: Record<string, any>;
  isDefault: boolean;
}

// ─── HEALTH_CARE ───────────────────────────────────────────────────────────
const HEALTH_CARE_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.HEALTH_CARE, type: TemplateType.WORKFLOW, name: 'Cobrança de Consultas', description: 'Workflow de cobrança para consultas e procedimentos', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Guia', trigger: 'appointment_completed', action: 'generate_invoice' }, { id: 2, name: 'Email com Boleto', trigger: 'invoice_generated', action: 'send_email', template: 'cobranca-consulta' }, { id: 3, name: 'Lembrete Vencimento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-vencimento' }, { id: 4, name: 'Notificar Recebível', trigger: 'invoice_overdue_7d', action: 'notify', target: 'billing' }] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.WORKFLOW, name: 'Onboarding Paciente', description: 'Fluxo de cadastro e boas-vindas para novo paciente', isDefault: true, content: { steps: [{ id: 1, name: 'Email Boas-vindas', trigger: 'patient_created', action: 'send_email', template: 'boas-vindas-paciente' }, { id: 2, name: 'Formulário Anamnese', trigger: 'timer_1d', action: 'send_email', template: 'anamnese-online' }, { id: 3, name: 'Lembrete Consulta', trigger: 'appointment_scheduled', action: 'send_sms', template: 'lembrete-consulta' }] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.WORKFLOW, name: 'Lembrete de Consulta', description: 'Confirmação e lembrete automático de consultas', isDefault: true, content: { steps: [{ id: 1, name: 'Confirmação 48h', trigger: 'appointment_48h', action: 'send_email', template: 'confirmar-consulta' }, { id: 2, name: 'Lembrete 24h', trigger: 'appointment_24h', action: 'send_sms', template: 'lembrete-24h' }, { id: 3, name: 'Lembrete 2h', trigger: 'appointment_2h', action: 'send_sms', template: 'lembrete-2h' }, { id: 4, name: 'No-show', trigger: 'appointment_missed', action: 'mark_no_show' }] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.WORKFLOW, name: 'Retorno Automático', description: 'Agendamento automático de retorno', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Retorno', trigger: 'appointment_completed', action: 'check_return', days: 30 }, { id: 2, name: 'Oferecer Agendamento', trigger: 'return_due_7d', action: 'send_email', template: 'agendar-retorno' }, { id: 3, name: 'Segundo Lembrete', trigger: 'timer_7d', action: 'send_sms', template: 'retorno-pendente' }] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.WORKFLOW, name: 'Controle de Convênios', description: 'Gestão de autorizações e faturamento com convênios', isDefault: false, content: { steps: [{ id: 1, name: 'Solicitar Autorização', trigger: 'procedure_scheduled', action: 'request_auth', insurance: true }, { id: 2, name: 'Aguardar Autorização', trigger: 'auth_requested', action: 'wait', timeout: '5d' }, { id: 3, name: 'Notificar Atraso', trigger: 'auth_timeout', action: 'notify', target: 'billing' }, { id: 4, name: 'Faturar Convênio', trigger: 'auth_approved', action: 'generate_claim' }] } },
  // 3 DASHBOARD
  { niche: Niche.HEALTH_CARE, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira de clínica/consultório', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables_by_insurance', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'no_show_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'professional', 'insurance'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.DASHBOARD, name: 'Dashboard de Agenda', description: 'Ocupação e fluxo de pacientes', isDefault: false, content: { widgets: [{ type: 'today_schedule', position: { x: 0, y: 0, w: 6, h: 6 } }, { type: 'occupancy_rate', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'patients_per_specialty', position: { x: 6, y: 4, w: 6, h: 2 } }], filters: ['professional', 'specialty', 'date'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.DASHBOARD, name: 'Dashboard de Convênios', description: 'Faturamento e inadimplência por convênio', isDefault: false, content: { widgets: [{ type: 'claims_by_insurance', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'denial_rate', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'avg_reimbursement_time', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'insurance'] } },
  // 4 EMAIL
  { niche: Niche.HEALTH_CARE, type: TemplateType.EMAIL, name: 'Boas-vindas Paciente', description: 'Email de boas-vindas para novo paciente', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{patient_name}},\n\nSeja bem-vindo(a) à nossa clínica! Estamos à disposição para cuidar da sua saúde.\n\nPara sua primeira consulta, chegue 15 minutos antes para preenchimento da ficha.', from: 'contato@{{company_domain}}' } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.EMAIL, name: 'Confirmação de Consulta', description: 'Email de confirmação de agendamento', isDefault: true, content: { subject: 'Consulta confirmada - {{date}} às {{time}}', body: 'Olá {{patient_name}},\n\nSua consulta está confirmada:\n\nData: {{date}}\nHorário: {{time}}\nProfissional: {{doctor_name}}\nEspecialidade: {{specialty}}\n\nEm caso de cancelamento, avise com 24h de antecedência.', from: 'agenda@{{company_domain}}' } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.EMAIL, name: 'Cobrança Particular', description: 'Email de cobrança para consulta particular', isDefault: true, content: { subject: 'Fatura de consulta - {{company_name}}', body: 'Olá {{patient_name}},\n\nReferente à consulta de {{date}}:\n\nValor: R$ {{amount}}\nVencimento: {{due_date}}\n\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.EMAIL, name: 'Lembrete de Retorno', description: 'Email lembrando sobre consulta de retorno', isDefault: false, content: { subject: 'Está na hora do seu retorno, {{patient_name}}!', body: 'Olá {{patient_name}},\n\nJá se passaram {{days_since_last_visit}} dias desde sua última consulta.\n\nAgende seu retorno pelo nosso app ou ligue para {{phone}}.\n\nSua saúde agradece!', from: 'contato@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.HEALTH_CARE, type: TemplateType.REPORT, name: 'DRE Clínica', description: 'DRE para clínica/consultório', isDefault: true, content: { sections: [{ title: 'Receita', items: ['consultas_particulares', 'convênios', 'procedimentos', 'exames'] }, { title: 'Custos', items: ['materiais_medicos', 'medicamentos', 'comissoes'] }, { title: 'Despesas', items: ['aluguel', 'pessoal', 'equipamentos', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.REPORT, name: 'Relatório de Produção', description: 'Produção por profissional e especialidade', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_consultas', 'taxa_ocupacao', 'no_show_pct'] }, { title: 'Por Profissional', items: ['consultas_por_medico', 'faturamento_por_medico'] }, { title: 'Por Especialidade', items: ['consultas_por_especialidade', 'ticket_medio_especialidade'] }], period: 'monthly' } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.REPORT, name: 'Relatório de Convênios', description: 'Análise de faturamento e glosas por convênio', isDefault: false, content: { sections: [{ title: 'Faturamento', items: ['total_faturado', 'total_recebido', 'glosas'] }, { title: 'Por Convênio', items: ['faturado_por_convenio', 'glosa_por_convenio', 'prazo_recebimento'] }, { title: 'Glosas', items: ['motivos_glosa', 'valor_recuperado'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.HEALTH_CARE, type: TemplateType.INVOICE, name: 'NFS-e Consulta', description: 'NFS-e para consulta médica', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.05', natureza: 'Consulta Médica', campos_adicionais: ['crm_medico', 'especialidade', 'cid', 'convenio'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.INVOICE, name: 'Guia TISS', description: 'Layout de guia TISS para convênios', isDefault: true, content: { formato: 'tiss', campos: ['guia_principal', 'dados_paciente', 'dados_convenio', 'procedimentos', 'valor_total'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.HEALTH_CARE, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias de Procedimentos', description: 'Categorias de serviços de saúde', isDefault: true, content: { categories: ['Consultas', 'Exames', 'Procedimentos', 'Cirurgias', 'Urgência', 'Retorno', 'Telemedicina', 'Check-up'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.PRODUCT_CATALOG, name: 'Especialidades Médicas', description: 'Lista de especialidades com códigos', isDefault: true, content: { specialties: ['Clínica Geral', 'Cardiologia', 'Dermatologia', 'Ginecologia', 'Ortopedia', 'Pediatria', 'Psicologia', 'Oftalmologia', 'Otorrino', 'Neurologia'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.PRODUCT_CATALOG, name: 'Margens por Procedimento', description: 'Margens sugeridas por tipo de procedimento', isDefault: false, content: { margins: [{ category: 'Consultas', margin: 0.70 }, { category: 'Exames', margin: 0.55 }, { category: 'Procedimentos', margin: 0.60 }, { category: 'Telemedicina', margin: 0.80 }, { category: 'Check-up', margin: 0.50 }] } },
  // 2 ONBOARDING
  { niche: Niche.HEALTH_CARE, type: TemplateType.ONBOARDING, name: 'Setup Clínica', description: 'Configuração inicial para clínica/consultório', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Clínica', fields: ['cnpj', 'razao_social', 'cnes'] }, { id: 2, title: 'Cadastrar Profissionais', action: 'create_doctors', fields: ['crm', 'especialidade'] }, { id: 3, title: 'Configurar Agenda', action: 'setup_schedule' }, { id: 4, title: 'Cadastrar Convênios', action: 'setup_insurance' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.ONBOARDING, name: 'Migração de Prontuários', description: 'Migrar dados de outro sistema de gestão médica', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Pacientes', action: 'export_patients' }, { id: 2, title: 'Importar Cadastros', action: 'import_patients' }, { id: 3, title: 'Importar Agendamentos', action: 'import_appointments' }, { id: 4, title: 'Validar Dados', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.HEALTH_CARE, type: TemplateType.NICHE_SPECIFIC, name: 'Prontuário Eletrônico', description: 'Estrutura base de prontuário eletrônico', isDefault: true, content: { sections: ['dados_paciente', 'anamnese', 'exame_fisico', 'hipotese_diagnostica', 'prescricao', 'evolucao', 'atestados'], required_fields: ['queixa_principal', 'historia_doenca', 'antecedentes'] } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.NICHE_SPECIFIC, name: 'Receita Médica Digital', description: 'Template de prescrição médica', isDefault: true, content: { fields: ['paciente', 'medicamento', 'posologia', 'duracao', 'observacoes'], auto_signature: true, controlado: false } },
  { niche: Niche.HEALTH_CARE, type: TemplateType.NICHE_SPECIFIC, name: 'Termo de Consentimento', description: 'Template de consentimento livre e esclarecido', isDefault: false, content: { sections: ['identificacao_paciente', 'descricao_procedimento', 'riscos', 'beneficios', 'alternativas', 'assinatura'] } },
];

// ─── EDUCATION ─────────────────────────────────────────────────────────────
const EDUCATION_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.EDUCATION, type: TemplateType.WORKFLOW, name: 'Cobrança de Mensalidade', description: 'Workflow de cobrança de mensalidades escolares', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Boleto', trigger: 'invoice_5d_before_due', action: 'send_email', template: 'boleto-mensalidade' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_date', action: 'send_sms', template: 'vencimento-hoje' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_3d', action: 'send_email', template: 'mensalidade-atrasada' }, { id: 4, name: 'Restrição de Acesso', trigger: 'invoice_overdue_30d', action: 'restrict_access' }, { id: 5, name: 'Negativação', trigger: 'invoice_overdue_60d', action: 'send_to_collection' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.WORKFLOW, name: 'Onboarding Aluno', description: 'Fluxo de matrícula e boas-vindas para novo aluno', isDefault: true, content: { steps: [{ id: 1, name: 'Confirmar Matrícula', trigger: 'enrollment_created', action: 'send_email', template: 'confirmacao-matricula' }, { id: 2, name: 'Dados do Aluno', trigger: 'timer_1d', action: 'send_email', template: 'completar-cadastro' }, { id: 3, name: 'Acesso ao Portal', trigger: 'enrollment_confirmed', action: 'create_access' }, { id: 4, name: 'Boas-vindas', trigger: 'access_created', action: 'send_email', template: 'boas-vindas-aluno' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.WORKFLOW, name: 'Rematrícula Automática', description: 'Processo de renovação de matrícula', isDefault: true, content: { steps: [{ id: 1, name: 'Aviso 60d', trigger: 'semester_ends_60d', action: 'send_email', template: 'aviso-rematricula' }, { id: 2, name: 'Abrir Rematrícula', trigger: 'semester_ends_30d', action: 'open_reenrollment' }, { id: 3, name: 'Lembrete 15d', trigger: 'semester_ends_15d', action: 'send_sms', template: 'rematricula-urgente' }, { id: 4, name: 'Lista de Inadimplentes', trigger: 'semester_ends_7d', action: 'generate_report', type: 'pending_enrollments' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.WORKFLOW, name: 'Aviso de Falta', description: 'Alerta automático de frequência baixa', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Faltas', trigger: 'daily_check', action: 'check_attendance', threshold: 0.75 }, { id: 2, name: 'Notificar Aluno', trigger: 'attendance_low', action: 'send_email', template: 'alerta-faltas' }, { id: 3, name: 'Notificar Responsável', trigger: 'attendance_critical', action: 'send_email', template: 'alerta-faltas-responsavel' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.WORKFLOW, name: 'Entrega de Certificado', description: 'Geração e envio de certificados', isDefault: false, content: { steps: [{ id: 1, name: 'Verificar Conclusão', trigger: 'course_completed', action: 'verify_completion' }, { id: 2, name: 'Gerar Certificado', trigger: 'completion_verified', action: 'generate_certificate' }, { id: 3, name: 'Enviar Certificado', trigger: 'certificate_generated', action: 'send_email', template: 'certificado-conclusao' }] } },
  // 3 DASHBOARD
  { niche: Niche.EDUCATION, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira da instituição de ensino', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'delinquency_rate', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'course', 'unit'] } },
  { niche: Niche.EDUCATION, type: TemplateType.DASHBOARD, name: 'Dashboard Acadêmico', description: 'Métricas de alunos, turmas e desempenho', isDefault: false, content: { widgets: [{ type: 'active_students', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'attendance_rate', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'enrollment_trend', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'courses_performance', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'course'] } },
  { niche: Niche.EDUCATION, type: TemplateType.DASHBOARD, name: 'Dashboard de Inadimplência', description: 'Acompanhamento de mensalidades em atraso', isDefault: false, content: { widgets: [{ type: 'total_overdue', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'aging_30_60_90', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'overdue_by_course', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'collection_rate', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period', 'course', 'unit'] } },
  // 4 EMAIL
  { niche: Niche.EDUCATION, type: TemplateType.EMAIL, name: 'Boas-vindas Aluno', description: 'Email de boas-vindas para novo aluno', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{student_name}},\n\nSua matrícula foi confirmada! Acesse o portal do aluno com suas credenciais.\n\nLogin: {{email}}\nSenha provisória: {{temp_password}}\n\nAlterne sua senha no primeiro acesso.', from: 'matricula@{{company_domain}}' } },
  { niche: Niche.EDUCATION, type: TemplateType.EMAIL, name: 'Boleto de Mensalidade', description: 'Email com boleto de mensalidade', isDefault: true, content: { subject: 'Mensalidade {{month}} - {{company_name}}', body: 'Olá {{student_name}},\n\nSua mensalidade de {{month}} no valor de R$ {{amount}} vence em {{due_date}}.\n\nBoleto em anexo ou pague via PIX: {{pix_key}}\n\nEm caso de dúvidas, entre em contato.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.EDUCATION, type: TemplateType.EMAIL, name: 'Mensalidade Atrasada', description: 'Email de aviso de mensalidade em atraso', isDefault: true, content: { subject: 'Mensalidade em atraso - {{company_name}}', body: 'Olá {{student_name}},\n\nSua mensalidade de {{month}} está {{days_overdue}} dias em atraso.\n\nValor atualizado: R$ {{amount_with_fine}}\n\nRegularize para evitar restrição de acesso.', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.EDUCATION, type: TemplateType.EMAIL, name: 'Certificado de Conclusão', description: 'Email com certificado de conclusão de curso', isDefault: false, content: { subject: 'Certificado de conclusão - {{course_name}}', body: 'Olá {{student_name}},\n\nParabéns! Você concluiu o curso {{course_name}}.\n\nSeu certificado está disponível no portal do aluno.\n\nContinue aprendendo!', from: 'academico@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.EDUCATION, type: TemplateType.REPORT, name: 'DRE Educação', description: 'DRE para instituição de ensino', isDefault: true, content: { sections: [{ title: 'Receita', items: ['mensalidades', 'matriculas', 'cursos_extras', 'eventos'] }, { title: 'Custos', items: ['professores', 'materiais_didaticos', 'infraestrutura'] }, { title: 'Despesas', items: ['aluguel', 'pessoal_admin', 'marketing', 'impostos'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido', 'ticket_medio_aluno'] }], period: 'monthly' } },
  { niche: Niche.EDUCATION, type: TemplateType.REPORT, name: 'Relatório de Matrículas', description: 'Análise de matrículas e evasão', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['total_matriculados', 'novos_matriculas', 'evasao', 'rematriculas'] }, { title: 'Por Curso', items: ['matriculas_por_curso', 'vagas_disponiveis', 'taxa_ocupacao'] }, { title: 'Evasão', items: ['motivos_evasao', 'taxa_retencao', 'alunos_risco'] }], period: 'monthly' } },
  { niche: Niche.EDUCATION, type: TemplateType.REPORT, name: 'Relatório de Inadimplência', description: 'Análise de inadimplência de mensalidades', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_inadimplente', 'taxa_inadimplencia', 'valor_recuperado'] }, { title: 'Aging', items: ['0_30d', '31_60d', '61_90d', 'acima_90d'] }, { title: 'Por Curso', items: ['inadimplencia_por_curso', 'acoes_cobranca'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.EDUCATION, type: TemplateType.INVOICE, name: 'NFS-e Educacional', description: 'NFS-e para serviço educacional', isDefault: true, content: { modelo: 'nfs-e', item_lista: '10.08', natureza: 'Serviço de Educação', campos_adicionais: ['curso', 'turma', 'periodo_letivo', 'aluno'] } },
  { niche: Niche.EDUCATION, type: TemplateType.INVOICE, name: 'Boleto de Mensalidade', description: 'Layout de boleto para mensalidade escolar', isDefault: true, content: { formato: 'boleto', campos: ['nosso_numero', 'valor', 'vencimento', 'aluno', 'curso', 'mes_referencia', 'multa_pct', 'juros_pct'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.EDUCATION, type: TemplateType.PRODUCT_CATALOG, name: 'Cursos e Modalidades', description: 'Categorias de cursos e modalidades de ensino', isDefault: true, content: { categories: ['Graduação', 'Pós-Graduação', 'Técnico', 'Extensão', 'Idiomas', 'Preparatório', 'Corporate', 'EAD'] } },
  { niche: Niche.EDUCATION, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Educacionais', description: 'Unidades de medida para educação', isDefault: true, content: { units: [{ code: 'MES', name: 'Mensalidade' }, { code: 'MOD', name: 'Módulo' }, { code: 'H', name: 'Hora/Aula' }, { code: 'CURSO', name: 'Curso Completo' }, { code: 'DISC', name: 'Disciplina' }, { code: 'TURMA', name: 'Turma' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.PRODUCT_CATALOG, name: 'Margens por Curso', description: 'Margens sugeridas por tipo de curso', isDefault: false, content: { margins: [{ category: 'Graduação', margin: 0.35 }, { category: 'Pós-Graduação', margin: 0.50 }, { category: 'Técnico', margin: 0.40 }, { category: 'Extensão', margin: 0.55 }, { category: 'Idiomas', margin: 0.45 }, { category: 'EAD', margin: 0.65 }] } },
  // 2 ONBOARDING
  { niche: Niche.EDUCATION, type: TemplateType.ONBOARDING, name: 'Setup Escola', description: 'Configuração inicial para escola/curso', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Escola', fields: ['cnpj', 'razao_social', 'mec_codigo'] }, { id: 2, title: 'Cadastrar Cursos', action: 'create_courses' }, { id: 3, title: 'Configurar Turmas', action: 'setup_classes' }, { id: 4, title: 'Cadastrar Alunos', action: 'import_students' }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.EDUCATION, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar dados de outro sistema escolar', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Dados', action: 'export' }, { id: 2, title: 'Importar Alunos', action: 'import' }, { id: 3, title: 'Importar Financeiro', action: 'import_finance' }, { id: 4, title: 'Importar Histórico', action: 'import_history' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.EDUCATION, type: TemplateType.NICHE_SPECIFIC, name: 'Diário de Classe', description: 'Template de diário de classe com frequência e notas', isDefault: true, content: { fields: ['data', 'conteudo_ministrado', 'metodologia', 'atividades', 'frequencia_alunos', 'observacoes'], auto_calculate_average: true } },
  { niche: Niche.EDUCATION, type: TemplateType.NICHE_SPECIFIC, name: 'Grade Curricular', description: 'Estrutura de grade curricular por curso', isDefault: true, content: { fields: ['curso', 'semestre', 'disciplina', 'carga_horaria', 'professor', 'pre_requisitos', 'tipo_obrigatoria_optativa'] } },
  { niche: Niche.EDUCATION, type: TemplateType.NICHE_SPECIFIC, name: 'Contrato de Prestação Educacional', description: 'Template de contrato educacional', isDefault: false, content: { sections: ['partes', 'objeto', 'valor_mensalidade', 'reajuste', 'desconto', 'cancelamento', 'deveres_aluno', 'foro'] } },
];

// ─── CONSTRUCTION ──────────────────────────────────────────────────────────
const CONSTRUCTION_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.CONSTRUCTION, type: TemplateType.WORKFLOW, name: 'Cobrança de Cliente', description: 'Workflow de cobrança para construção civil', isDefault: true, content: { steps: [{ id: 1, name: 'Enviar Fatura', trigger: 'invoice_created', action: 'send_email', template: 'fatura-obra' }, { id: 2, name: 'Lembrete Vencimento', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-vencimento' }, { id: 3, name: 'Aviso Atraso', trigger: 'invoice_overdue_5d', action: 'send_email', template: 'aviso-atraso-obra' }, { id: 4, name: 'Notificar Diretoria', trigger: 'invoice_overdue_15d', action: 'notify', target: 'director' }, { id: 5, name: 'Suspender Obra', trigger: 'invoice_overdue_30d', action: 'halt_project' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.WORKFLOW, name: 'Onboarding de Obra', description: 'Fluxo de inicialização de nova obra', isDefault: true, content: { steps: [{ id: 1, name: 'Criar Projeto', trigger: 'project_created', action: 'create_project' }, { id: 2, name: 'Cronograma Físico', trigger: 'timer_1d', action: 'request_schedule' }, { id: 3, name: 'Alocação de Equipe', trigger: 'schedule_ready', action: 'allocate_team' }, { id: 4, name: 'Pedido de Materiais', trigger: 'team_allocated', action: 'create_material_request' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.WORKFLOW, name: 'Pedido de Compra', description: 'Fluxo de aprovação de pedidos de compra', isDefault: true, content: { steps: [{ id: 1, name: 'Solicitar Compra', trigger: 'purchase_requested', action: 'create_request' }, { id: 2, name: 'Aprovar Gerente', trigger: 'request_created', action: 'notify', target: 'manager' }, { id: 3, name: 'Cotações', trigger: 'request_approved', action: 'request_quotes', min_quotes: 3 }, { id: 4, name: 'Aprovar Diretor', trigger: 'quotes_received', action: 'notify', target: 'director', min_value: 10000 }, { id: 5, name: 'Emitir Pedido', trigger: 'quotes_approved', action: 'create_purchase_order' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.WORKFLOW, name: 'Medição de Serviço', description: 'Processo de medição e faturamento de serviços', isDefault: false, content: { steps: [{ id: 1, name: 'Registrar Medição', trigger: 'measurement_done', action: 'create_measurement' }, { id: 2, name: 'Aprovar Engenheiro', trigger: 'measurement_created', action: 'notify', target: 'engineer' }, { id: 3, name: 'Aprovar Cliente', trigger: 'measurement_approved', action: 'send_email', template: 'aprovacao-mediacao' }, { id: 4, name: 'Faturar', trigger: 'client_approved', action: 'generate_invoice' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.WORKFLOW, name: 'Inspeção de Qualidade', description: 'Workflow de controle de qualidade em obra', isDefault: false, content: { steps: [{ id: 1, name: 'Agendar Inspeção', trigger: 'milestone_reached', action: 'schedule_inspection' }, { id: 2, name: 'Realizar Inspeção', trigger: 'inspection_date', action: 'create_checklist' }, { id: 3, name: 'Aprovar/Rejeitar', trigger: 'inspection_done', action: 'update_status' }, { id: 4, name: 'Rework', trigger: 'inspection_failed', action: 'create_rework_task' }] } },
  // 3 DASHBOARD
  { niche: Niche.CONSTRUCTION, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira para construtora', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'receivables', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'project_margin', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period', 'project'] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.DASHBOARD, name: 'Dashboard de Obras', description: 'Acompanhamento de obras em andamento', isDefault: false, content: { widgets: [{ type: 'active_projects', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'project_timeline', position: { x: 4, y: 0, w: 8, h: 4 } }, { type: 'budget_vs_actual', position: { x: 0, y: 4, w: 6, h: 4 } }, { type: 'physical_progress', position: { x: 6, y: 4, w: 6, h: 4 } }], filters: ['project', 'status'] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.DASHBOARD, name: 'Dashboard de Compras', description: 'Métricas de compras e fornecedores', isDefault: false, content: { widgets: [{ type: 'pending_orders', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'purchase_by_category', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'supplier_performance', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'cost_variance', position: { x: 0, y: 4, w: 12, h: 4 } }], filters: ['period', 'project', 'supplier'] } },
  // 4 EMAIL
  { niche: Niche.CONSTRUCTION, type: TemplateType.EMAIL, name: 'Boas-vindas Cliente', description: 'Email de boas-vindas para novo cliente', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nSeu projeto foi iniciado com sucesso! Acompanhe o andamento pelo portal.\n\nEngenheiro responsável: {{engineer_name}}\nPrevisão de conclusão: {{estimated_completion}}\n\nAtenciosamente,', from: 'contato@{{company_domain}}' } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.EMAIL, name: 'Fatura de Obra', description: 'Email com fatura de medição/serviço', isDefault: true, content: { subject: 'Fatura #{{invoice_number}} - {{project_name}}', body: 'Olá {{customer_name}},\n\nReferente à medição {{measurement_number}} do projeto {{project_name}}:\n\nValor: R$ {{amount}}\nVencimento: {{due_date}}\n\nPIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.EMAIL, name: 'Atualização de Obra', description: 'Relatório de progresso da obra', isDefault: false, content: { subject: 'Atualização semanal - {{project_name}}', body: 'Olá {{customer_name}},\n\nProgresso da obra {{project_name}}:\n- Físico: {{physical_progress}}%\n- Financeiro: {{financial_progress}}%\n- Atividades da semana: {{weekly_activities}}\n- Próximos passos: {{next_steps}}\n\nDúvidas? Entre em contato.', from: 'projetos@{{company_domain}}' } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.EMAIL, name: 'Pedido de Aprovação', description: 'Email pedindo aprovação de medição', isDefault: false, content: { subject: 'Aprovação de medição - {{project_name}}', body: 'Olá {{customer_name}},\n\nA medição {{measurement_number}} está pronta para sua aprovação.\n\nValor: R$ {{amount}}\nServiços: {{services_description}}\n\nAcesse o portal para aprovar.', from: 'projetos@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.CONSTRUCTION, type: TemplateType.REPORT, name: 'DRE Construtora', description: 'DRE para empresa de construção civil', isDefault: true, content: { sections: [{ title: 'Receita', items: ['vendas_unidades', 'servicos_obra', 'projetos'] }, { title: 'Custos', items: ['materiais', 'mao_obra', 'subempreiteiros', 'equipamentos'] }, { title: 'Despesas', items: ['aluguel', 'pessoal_admin', 'marketing', 'impostos', 'seguros'] }, { title: 'Resultado', items: ['lucro_bruto', 'margem_obra', 'lucro_liquido'] }], period: 'monthly' } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.REPORT, name: 'Relatório de Obra', description: 'Cronograma físico-financeiro por obra', isDefault: true, content: { sections: [{ title: 'Resumo', items: ['progresso_fisico', 'progresso_financeiro', 'desvio_orcamento'] }, { title: 'Cronograma', items: ['etapas_concluidas', 'etapas_atrasadas', 'etapas_proximas'] }, { title: 'Custo', items: ['orcado_vs_real', 'variacoes_significativas', 'previsao_conclusao'] }], period: 'monthly' } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.REPORT, name: 'Relatório de Compras', description: 'Análise de compras e fornecedores', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_compras', 'pedidos_pendentes', 'pedidos_atrasados'] }, { title: 'Por Categoria', items: ['materiais', 'equipamentos', 'servicos', 'outros'] }, { title: 'Por Fornecedor', items: ['ranking_fornecedores', 'atrasos_entrega', 'desvio_preco'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.CONSTRUCTION, type: TemplateType.INVOICE, name: 'NF-e Materiais', description: 'NF-e para venda de materiais de construção', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Material de Construção', campos_adicionais: ['obra_destino', 'pedido_compra'] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.INVOICE, name: 'NFS-e Serviços de Obra', description: 'NFS-e para serviços de construção', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.08', natureza: 'Serviço de Construção Civil', campos_adicionais: ['obra', 'mediacao_numero', 'art_rrt', 'crea'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.CONSTRUCTION, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias de Materiais', description: 'Categorias de materiais de construção', isDefault: true, content: { categories: ['Cimento e Argamassa', 'Aço e Ferro', 'Madeira', 'Elétrica', 'Hidráulica', 'Acabamento', 'Ferramentas', 'Pintura'] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Construção', description: 'Unidades de medida para construção', isDefault: true, content: { units: [{ code: 'M2', name: 'Metro Quadrado' }, { code: 'M3', name: 'Metro Cúbico' }, { code: 'KG', name: 'Quilograma' }, { code: 'UN', name: 'Unidade' }, { code: 'M', name: 'Metro Linear' }, { code: 'SACO', name: 'Saco 50kg' }, { code: 'BARRA', name: 'Barra 12m' }, { code: 'L', name: 'Litro' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.PRODUCT_CATALOG, name: 'Margens por Serviço', description: 'Margens sugeridas por tipo de serviço de construção', isDefault: false, content: { margins: [{ category: 'Fundação', margin: 0.25 }, { category: 'Estrutura', margin: 0.20 }, { category: 'Acabamento', margin: 0.35 }, { category: 'Instalações', margin: 0.30 }, { category: 'Projetos', margin: 0.50 }] } },
  // 2 ONBOARDING
  { niche: Niche.CONSTRUCTION, type: TemplateType.ONBOARDING, name: 'Setup Construtora', description: 'Configuração inicial para construtora', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Empresa', fields: ['cnpj', 'razao_social', 'crea', 'rt'] }, { id: 2, title: 'Cadastrar Obras', action: 'create_projects' }, { id: 3, title: 'Cadastrar Fornecedores', action: 'import_suppliers' }, { id: 4, title: 'Configurar Custos', fields: ['centros_custo', 'categorias_despesa'] }, { id: 5, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar dados de outro sistema de construção', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar Dados', action: 'export' }, { id: 2, title: 'Importar Obras', action: 'import_projects' }, { id: 3, title: 'Importar Fornecedores', action: 'import_suppliers' }, { id: 4, title: 'Importar Financeiro', action: 'import_finance' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.CONSTRUCTION, type: TemplateType.NICHE_SPECIFIC, name: 'B.U.P. (Budget Unitário)', description: 'Template de orçamento unitário por serviço', isDefault: true, content: { fields: ['servico', 'unidade', 'quantidade', 'custo_material', 'custo_mao_obra', 'custo_equipe', 'bdi_pct', 'preco_venda'], bdi_default: 0.25 } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.NICHE_SPECIFIC, name: 'Diário de Obra', description: 'Registro diário de ocorrências na obra', isDefault: true, content: { fields: ['data', 'clima', 'equipe_presente', 'servicos_executados', 'materiais_recebidos', 'ocorrencias', 'fotos', 'observacoes'] } },
  { niche: Niche.CONSTRUCTION, type: TemplateType.NICHE_SPECIFIC, name: 'Contrato de Empreitada', description: 'Template de contrato de empreitada', isDefault: false, content: { sections: ['partes', 'objeto', 'valor_global', 'cronograma', 'condicoes_pagamento', 'multas', 'garantias', 'seguro_obras', 'recebimento_provisorio', 'foro'] } },
];

// ─── OTHER (Genérico para nichos adicionais: Beleza, Fitness, Jurídico, etc.) ──
const OTHER_TEMPLATES: TemplateSeed[] = [
  // 5 WORKFLOW
  { niche: Niche.OTHER, type: TemplateType.WORKFLOW, name: 'Cobrança Genérica', description: 'Workflow de cobrança padrão', isDefault: true, content: { steps: [{ id: 1, name: 'Lembrete Email', trigger: 'invoice_due_3d', action: 'send_email', template: 'lembrete-pagamento' }, { id: 2, name: 'Segundo Aviso', trigger: 'invoice_overdue_3d', action: 'send_email', template: 'segundo-aviso' }, { id: 3, name: 'Ligação', trigger: 'invoice_overdue_7d', action: 'notify', target: 'billing' }, { id: 4, name: 'Suspender Serviço', trigger: 'invoice_overdue_30d', action: 'suspend_service' }] } },
  { niche: Niche.OTHER, type: TemplateType.WORKFLOW, name: 'Onboarding de Cliente', description: 'Fluxo de boas-vindas genérico', isDefault: true, content: { steps: [{ id: 1, name: 'Boas-vindas', trigger: 'customer_created', action: 'send_email', template: 'boas-vindas' }, { id: 2, name: 'Completar Perfil', trigger: 'timer_2d', action: 'send_email', template: 'completar-perfil' }, { id: 3, name: 'Primeiro Follow-up', trigger: 'timer_7d', action: 'send_email', template: 'follow-up-7d' }] } },
  { niche: Niche.OTHER, type: TemplateType.WORKFLOW, name: 'Agendamento', description: 'Workflow de agendamento com confirmação', isDefault: true, content: { steps: [{ id: 1, name: 'Confirmar', trigger: 'appointment_created', action: 'send_email', template: 'confirmacao' }, { id: 2, name: 'Lembrete 24h', trigger: 'appointment_24h', action: 'send_sms', template: 'lembrete-24h' }, { id: 3, name: 'Lembrete 1h', trigger: 'appointment_1h', action: 'send_sms', template: 'lembrete-1h' }] } },
  { niche: Niche.OTHER, type: TemplateType.WORKFLOW, name: 'Follow-up Pós-Venda', description: 'Acompanhamento pós-venda genérico', isDefault: false, content: { steps: [{ id: 1, name: 'NPS', trigger: 'sale_completed_3d', action: 'send_email', template: 'nps' }, { id: 2, name: 'Oferta Recorrente', trigger: 'timer_30d', action: 'send_email', template: 'oferta-recorrente' }] } },
  { niche: Niche.OTHER, type: TemplateType.WORKFLOW, name: 'Renovação de Contrato', description: 'Workflow de renovação de contrato', isDefault: false, content: { steps: [{ id: 1, name: 'Alerta 60d', trigger: 'contract_expires_60d', action: 'notify', target: 'commercial' }, { id: 2, name: 'Proposta Renovação', trigger: 'timer_10d', action: 'send_email', template: 'proposta-renovacao' }, { id: 3, name: 'Follow-up', trigger: 'timer_15d', action: 'send_email', template: 'renovacao-followup' }] } },
  // 3 DASHBOARD
  { niche: Niche.OTHER, type: TemplateType.DASHBOARD, name: 'Dashboard Financeiro', description: 'Visão financeira geral', isDefault: true, content: { widgets: [{ type: 'revenue', position: { x: 0, y: 0, w: 6, h: 4 } }, { type: 'expenses', position: { x: 6, y: 0, w: 6, h: 4 } }, { type: 'cashflow', position: { x: 0, y: 4, w: 8, h: 4 } }, { type: 'margin', position: { x: 8, y: 4, w: 4, h: 4 } }], filters: ['period'] } },
  { niche: Niche.OTHER, type: TemplateType.DASHBOARD, name: 'Dashboard Operacional', description: 'Métricas operacionais gerais', isDefault: false, content: { widgets: [{ type: 'daily_metrics', position: { x: 0, y: 0, w: 4, h: 4 } }, { type: 'tasks_overview', position: { x: 4, y: 0, w: 4, h: 4 } }, { type: 'customer_stats', position: { x: 8, y: 0, w: 4, h: 4 } }], filters: ['period', 'department'] } },
  { niche: Niche.OTHER, type: TemplateType.DASHBOARD, name: 'Dashboard de Vendas', description: 'Análise de vendas e clientes', isDefault: false, content: { widgets: [{ type: 'sales_trend', position: { x: 0, y: 0, w: 8, h: 4 } }, { type: 'top_customers', position: { x: 8, y: 0, w: 4, h: 4 } }, { type: 'sales_by_source', position: { x: 0, y: 4, w: 6, h: 4 } }], filters: ['period'] } },
  // 4 EMAIL
  { niche: Niche.OTHER, type: TemplateType.EMAIL, name: 'Boas-vindas', description: 'Email de boas-vindas genérico', isDefault: true, content: { subject: 'Bem-vindo(a) à {{company_name}}!', body: 'Olá {{customer_name}},\n\nObrigado por escolher a {{company_name}}!\n\nEstamos à disposição para ajudá-lo.', from: 'contato@{{company_domain}}' } },
  { niche: Niche.OTHER, type: TemplateType.EMAIL, name: 'Cobrança Amigável', description: 'Email de cobrança amigável', isDefault: true, content: { subject: 'Lembrete de pagamento - {{company_name}}', body: 'Olá {{customer_name}},\n\nSua fatura de R$ {{amount}} vence em {{due_date}}.\n\nChave PIX: {{pix_key}}', from: 'financeiro@{{company_domain}}' } },
  { niche: Niche.OTHER, type: TemplateType.EMAIL, name: 'Follow-up', description: 'Email de follow-up genérico', isDefault: false, content: { subject: 'Como podemos ajudar, {{customer_name}}?', body: 'Olá {{customer_name}},\n\nGostaríamos de saber como está sua experiência.\n\nPrecisa de algo? Estamos aqui!', from: 'contato@{{company_domain}}' } },
  { niche: Niche.OTHER, type: TemplateType.EMAIL, name: 'Newsletter Mensal', description: 'Resumo mensal de novidades', isDefault: false, content: { subject: 'Novidades do mês - {{company_name}}', body: 'Olá {{customer_name}},\n\nConfira as novidades do mês:\n{{monthly_highlights}}\n\nAté a próxima!', from: 'news@{{company_domain}}' } },
  // 3 REPORT
  { niche: Niche.OTHER, type: TemplateType.REPORT, name: 'DRE Genérico', description: 'DRE padrão para qualquer nicho', isDefault: true, content: { sections: [{ title: 'Receita', items: ['vendas', 'servicos', 'recorrentes'] }, { title: 'Deduções', items: ['devolucoes', 'descontos', 'impostos'] }, { title: 'Custos', items: ['cmv', 'custo_servico'] }, { title: 'Despesas', items: ['pessoal', 'operacional', 'marketing', 'administrativo'] }, { title: 'Resultado', items: ['lucro_bruto', 'lucro_liquido', 'margem'] }], period: 'monthly' } },
  { niche: Niche.OTHER, type: TemplateType.REPORT, name: 'Fluxo de Caixa', description: 'Relatório de fluxo de caixa', isDefault: true, content: { sections: [{ title: 'Entradas', items: ['recebimentos', 'outras_entradas'] }, { title: 'Saídas', items: ['pagamentos', 'investimentos', 'outras_saidas'] }, { title: 'Saldo', items: ['saldo_dia', 'saldo_acumulado', 'projecao_30d'] }], period: 'daily' } },
  { niche: Niche.OTHER, type: TemplateType.REPORT, name: 'Relatório de Clientes', description: 'Análise de carteira de clientes', isDefault: false, content: { sections: [{ title: 'Resumo', items: ['total_clientes', 'novos_mes', 'churn_rate'] }, { title: 'Segmentação', items: ['por_segmento', 'por_faixa_receita'] }, { title: 'Inadimplência', items: ['total_atrasado', 'aging'] }], period: 'monthly' } },
  // 2 INVOICE
  { niche: Niche.OTHER, type: TemplateType.INVOICE, name: 'NF-e Genérica', description: 'NF-e padrão para venda de mercadorias', isDefault: true, content: { modelo: '55', serie: '1', cfop: '5102', cst_icms: '00', csosn: '102', natureza: 'Venda de Mercadoria', campos_adicionais: [] } },
  { niche: Niche.OTHER, type: TemplateType.INVOICE, name: 'NFS-e Genérica', description: 'NFS-e padrão para prestação de serviços', isDefault: true, content: { modelo: 'nfs-e', item_lista: '01.07', natureza: 'Prestação de Serviços', campos_adicionais: ['retencoes'] } },
  // 3 PRODUCT_CATALOG
  { niche: Niche.OTHER, type: TemplateType.PRODUCT_CATALOG, name: 'Categorias Genéricas', description: 'Categorias de produtos/serviços padrão', isDefault: true, content: { categories: ['Produtos', 'Serviços', 'Assinaturas', 'Combos', 'Personalizados'] } },
  { niche: Niche.OTHER, type: TemplateType.PRODUCT_CATALOG, name: 'Unidades Padrão', description: 'Unidades de medida genéricas', isDefault: true, content: { units: [{ code: 'UN', name: 'Unidade' }, { code: 'H', name: 'Hora' }, { code: 'KG', name: 'Quilograma' }, { code: 'M', name: 'Metro' }, { code: 'L', name: 'Litro' }, { code: 'MENS', name: 'Mensalidade' }, { code: 'PROJ', name: 'Projeto' }] } },
  { niche: Niche.OTHER, type: TemplateType.PRODUCT_CATALOG, name: 'Margens Padrão', description: 'Margens sugeridas genéricas', isDefault: false, content: { margins: [{ category: 'Produtos', margin: 0.35 }, { category: 'Serviços', margin: 0.55 }, { category: 'Assinaturas', margin: 0.60 }, { category: 'Combos', margin: 0.40 }] } },
  // 2 ONBOARDING
  { niche: Niche.OTHER, type: TemplateType.ONBOARDING, name: 'Setup Inicial', description: 'Configuração inicial genérica', isDefault: true, content: { steps: [{ id: 1, title: 'Dados da Empresa', fields: ['cnpj', 'razao_social', 'endereco'] }, { id: 2, title: 'Configurar Serviços', action: 'create_services' }, { id: 3, title: 'Cadastrar Clientes', action: 'import_clients' }, { id: 4, title: 'Concluir', action: 'finish' }] } },
  { niche: Niche.OTHER, type: TemplateType.ONBOARDING, name: 'Migração de Dados', description: 'Migrar dados de outro sistema', isDefault: false, content: { steps: [{ id: 1, title: 'Exportar', action: 'export' }, { id: 2, title: 'Importar Clientes', action: 'import_clients' }, { id: 3, title: 'Importar Produtos', action: 'import_products' }, { id: 4, title: 'Importar Financeiro', action: 'import_finance' }, { id: 5, title: 'Validar', action: 'validate' }] } },
  // 3 NICHE_SPECIFIC
  { niche: Niche.OTHER, type: TemplateType.NICHE_SPECIFIC, name: 'Formulário Personalizado', description: 'Template base para formulários customizáveis', isDefault: true, content: { fields: [], configurable: true, types_available: ['text', 'number', 'select', 'checkbox', 'date', 'file'] } },
  { niche: Niche.OTHER, type: TemplateType.NICHE_SPECIFIC, name: 'Checklist de Processo', description: 'Checklist genérico para processos internos', isDefault: true, content: { items: [], configurable: true, auto_assign: false } },
  { niche: Niche.OTHER, type: TemplateType.NICHE_SPECIFIC, name: 'Integração Personalizada', description: 'Template para configurar integrações com APIs externas', isDefault: false, content: { supported_types: ['webhook', 'rest_api', 'soap', 'ftp'], auth_methods: ['api_key', 'oauth2', 'basic_auth', 'bearer'] } },
];

export { HEALTH_CARE_TEMPLATES, EDUCATION_TEMPLATES, CONSTRUCTION_TEMPLATES, OTHER_TEMPLATES };
